apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4z925h0o+0imlh5hBS3z5Q==,iv:jFs2AagLvk5959tY2Vl3VGAe0eHpOmDIlYk/QZigipg=,tag:3AqkcNGfJm9jYLfs4W8s3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:D4eeZJKZE5UoJ4RLNa4yP1TkB2po+Hir5KTuuvbeCgTZV7sTSg==,iv:L28AhD62NyMny0QASROPiXmlxmXi1ZvnVGzcLVTXxwY=,tag:9DhbPaVeJCy0xx40QGQGAQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ftsqCeK12pxAqo7u6zW6DLjh,iv:T1NEGLmNkUhdmWXjJIzpB52HHm1TS2iEn83HK0rGnOo=,tag:ENJc5p7WUtD3Lpy/swdGxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaERQNERRdkY4eENjaHpr
            dTNqOWxpNjRpZTIxTHo5UjA1bVBFRk80UlUwCi9UdStWQmdDdmMrbWFyS1BGRUxR
            bGdtay9rM0tucFp1KzhsSWtCd1pTeDQKLS0tIEZKRmdQMjlYR3M1MGx3WUQwbGhp
            MGhEN1NlRTgvTDVzWkE3V1ExRitpMjQKRVRsYvaFidOWfZ/4q/wsWXne//frH6Dp
            Iau7cIo5cg2lr7IGOdL/CJ8pZoCWT7fI5fP5HFznEtU8JIF7X9/k/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:JZI2HwtxufP1ShhXO/3Z9T0LdVWokryX1hpa+Liwx+2cMZqi+pX3Ud43RzasyLm6Dju4Qz3dpPYSnt9DGgR7nJvP+HXwyFCp+8SSWINOUoAyM2gRPcBaCi58HbETW54BSZ/eq6EWUPW+mfpEP+MKOInlo3n8rIR9Yoa9xW6DN30=,iv:BadWqjA+4KCPDwzlvwNxSRYojQNSIHll9qPzScBsMgI=,tag:74MagtwELt0PxWXULn2KnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
