apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tiAi8VRuayKfzvgiCAjGKQ==,iv:rXPXCroiMUBWxZGSdntTZqLBN2qR9gPfOx+bzCFgZv0=,tag:1qQMaPic8cnu/ig7KDabaw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:9fjt7FhyRjg6FkthuWx7UC29yltdhXIi9ZEw8ZusecdFCrie6Q==,iv:7hDqg7MpAud97E1aaMSWo13o8Jlr5stXbTsD/VjipNE=,tag:od5hdaZTOUdfnyIv1XXHQA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:jHSWoFbICc3j23qKWKTrBGIz,iv:ia+t431gOgaGtGcQQJKMeHnHfAlGMNtS6nTPmsRL05M=,tag:wpqahIck2k9SVCNTSxSgNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTHBYU0pIR3dleEh4L0xq
            UVUrWTltaTM3WnZRa0pYTzBiR292NHpmL1cwCmwxdEcrdW54a01NYVVwd1cySjhU
            MEszKzhxZFF6RWRoY1pPQTJlbzBhOTgKLS0tIFFVaHFXcWVSZ21kOURGYnNVUVRH
            ZXcrU0pWRlJnK244K25WT0J2ZVA4SW8Kg4i6wCQjWYzW2xaD1RDTErm+sygSONcT
            BCVyTFLdKuNojsb+YYAr5OjUVQMTglnGxCEzoPhNCarwJZMD0/+IYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T22:46:48Z"
    mac: ENC[AES256_GCM,data:op+bZWYywpXiN0HgM5iSM+egm/UZ9HX83kfhHSFhSGmCEQGSwg4K9DW2X9n6+OcKsqPNB1745jhhCp/upc/eO4O2eZpMVAL0nKu5HfYq5myCokW6astFdVi3wvztZNoRItwHTfnTWGgkhJly9e4KBB9LhxosmnvhA8Jmx1JXQCo=,iv:ZV5jgF+6cEjSg6qnrx7hvySu/DNPP5PiG5Sbj6zvnuA=,tag:C5jesuHW5ndPizbB80acUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
