apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KnxxQqpk5wfwksMocdKhsQ==,iv:e1f/RJ/HNjPwmx0sjtVPg4Tz6Rs1IEG1rN095Prwjqk=,tag:jluxM3u9Yy4Z6dldNX1zyQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:sbMVkhytuckZ7/DDxrd4DH3WBd2QgUY6/jYdcw1kwVFOm/fMQA==,iv:jIRakQ+Mc7p7jAEO35qSwBIXdUtFPFHdpK3aj4jFRJ4=,tag:zLKMaiRNHmgzj4N7tPK+kg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:pgEgyEALneUm0V2+Xdx2gt2A,iv:jZYq3RW28NHcs9cwhwqZfCVePHD8V1Gvrfy1C0DHKME=,tag:sQnM2z1I+8GR6XZghkdJmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ1hydS9mMVBPNjhzSFVZ
            dWpiYnJYVWcrYldlSTdzY2FtZFh4UGxmcGlRClpwZUorNkFkc3RVN2IwM0NJZTdJ
            QjJFMm5wSjZJSjNMVmtOb1JDQlQyNkkKLS0tIGk3cXBHenBIT0RkRHY4RUNTd2ZZ
            SmF0Yk53eUkreTZRSkJ6ZGZQWUZSMFkKsBDDB/iJVXUDzfOtTZG8aYlqD0HnFlE0
            l6FAmSH5JvTk5UCRwskQPlvrgA2+S0XedgIxAnqcIgsQQF9jA/VoCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:22:23Z"
    mac: ENC[AES256_GCM,data:tzXityW4xpAn0bETwHrO1ZrYsRorEJ2HHivWyc7TTvuJe78x0Jbj4iuKVWB/U+4QeaZe+ulqMr6q8zWKWrRFHIv87LdSUaY101Ys7h6khJ3fq/OlXktHQecOANxheeNr4JxyVShZK8LV5ZbDcRUck6AMhR5Yq4s6XeCf6jILTBs=,iv:+wlHnplIrwWNkLxkRkPOIpcMWyTQ3cTiujmp/QiVj5w=,tag:Ly/FJjs5gNBhuVKLsss/TA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
