apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IiyBHwCw0M0=,iv:oFgt500CAP9WpXkmAHAXTQSGucsPqY2cMB9i75FvX/w=,tag:pnwPLiTUGNq6DV0Z9bD9nw==,type:str]
    password: ENC[AES256_GCM,data:JODLZUn0Vs7Z6MaBlB1etcjgvrKfRvWLC5+4SFpcInxIb56VG2zT49yQGujd8FsBduv0gotwgz31aXXb3RNs9Q==,iv:p4kDjdqw0Xfd2G+6Sa/GNzSC4YZqSMa0pj8OI8b5Bbo=,tag:nmBFngk67Wti1/UygTGrQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV1JJUThMZGpYL3A0WG5s
            dGFTNmhwZThlU01QUHBvdDdEbllWY3g3U1VzCms0eDg5M1UrMjdMbFFqcFJDbkpa
            THlCNk5lS3Bib0kyZTE4TnAvcDB5TFEKLS0tIExDd2x4ZlNmOW9kOEVvZ0xnOTRM
            MzBCaXgvUlU3bmlmNlFNbTNwSFRqeVUKJu640cSQLiICo9QxpWPI+KKZdz2MLtwi
            RR0o7N4So81DDUAlCg/HLS6wdLzV6pHvduwyNRB6ezy1A7wGS/iTLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T20:00:57Z"
    mac: ENC[AES256_GCM,data:jThFSS8NafTC+sxSOWC5CMpVa8Cy/FKiD0RDG0dDLHDPFtMkeP1om45fuMX19BQbGx3pTFO9iOrN9qfFnt3RWOCtGD1Ny1ic8vKXiBe8GvfVwIWRzaBrBR+aRAz8HVFTYdcpv5HcyHDkU4xZ/SsoRf/uY1eZGf/MacA0jVx7KVg=,iv:wY3yBpT5BjwPI7V2ErMuuW0teanKnXD+ujOStGTcz7U=,tag:2P5cxZi+OAz8+G9iQbf59Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
