apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:PtR4YwFeio5brPoZ0+IVpQs15O18wC1PiD69y60Vv1J9Qa0Q94jJQDY5zcFlpaKwhNs7nXmr2VnVLnKBLkTwRufjxbJayaGp1rjG073Jj+I+gYrIAdtQuv6L8HZptRPZU7ZUdcdRNrtynMEoIFhGF39BgFXWy2LYWpJTR2tmgN+KsKPfbj5icEC5jbFucQeMrJmfXIsJ6n/hu+aTxKe2zjEpv5dBOZFF9b7x+5KiB8leXCj0npOVc5hKwyVr7TjTTevzrJh051BplsInzkFTVoQVijkxYcHrtHJAxTeOZ9CFwET0KTh6nVlwN/exoyIDNaR9F7BTQkKR4YP3Q09FBqAs3jHLY5XjH8z5jwwtDYrYSZpXZEHNjjCnIka4FKZV8bzrBA==,iv:f/Nrs70zuqGfASA4j/qKyuoCaWgqfk/8vQJETactffk=,tag:+lMUhmpbAnSEJeUJ/vrkbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVhWck1ablJ6UnVGQzNJ
            TUN4cWZMZjZwMk1CamNHS3poN3JBdW5tbm5vCkRqUXJPUjZHSGp0YlJhdDRjOXhG
            QUwvUVlCUStCZzlzNjRQUW5keUd3QzQKLS0tIEpaQytDWUhIRVh3VWhBdVVBbEdq
            YXkvWXpwNjUzWUVhN1BvY0RhWWEwTjQKrngN5f9bqQ8c7wvA3Iai63ig7TZrrTDV
            hjLceWsH3UiMTN27ZOJp9IUAR0TNmI1PRgoR1oQ2K5DyNiBveOmaIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:yQTsjj/tO9WD3xfwhP/CuWydfsv5TJ9nqKMm/ZWYrehcOhBvWBXeO00mfLb3ulE1DOykFY4a0vYdiPjQiIwei/b/JYnysY5r9oiij6W5k3RR75Xk2DPmOzj8Vaj9PZAYOPW4Fx1SU/m5V3Ozy0LcVDrPs/boCzRqRhMYdEAJeyc=,iv:JsVE/1yM8cu+W9hvs4VVFoX8fL4rekU/NfIFtIza0e0=,tag:5yrwVjqurAC/i49Vjl/+oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
