kind: ENC[AES256_GCM,data:uVD1vHcK,iv:5af5/rekfCZVWGmo9vYbuxUxR0pYuqETNsYj/ApuwEE=,tag:Zj3Lt6ZfGge3xzr+fY0jEQ==,type:str]
ansible_user: ENC[AES256_GCM,data:lr6SeQ==,iv:JZURkzjSedpZ5IYzK1HL7Fxd5V0YgBl88soq3DK5MEM=,tag:fK19AZVhEd4rqQudg7iKhQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AVy47gewN375,iv:DCkcz6sqo05iqJOdpXzcAntNnXS+OSc0mdgABS0IMyM=,tag:+IIM9mwsCHtOXUMbGAyPjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY1NEN1VuSDltcFp3THhj
            QTNPRTJwYVY2L2kwMGdIM2RpUS9VbDIrQzMwCk15akpUcnF4YnNkVHVSV1NZSlV5
            LzVrZnUwZEZHQUpNRGJ1SUhBK0Z2NWsKLS0tIEx2WndTU2RCWXhiaDFITWgzaGhk
            bTFDNkhiRDRoWXJOSFpSOEgxcVA4UmsK3OtPNrztIwmsku1pJ7mxMZeuiwka58b/
            AuSPacnR2aN0UvlIe1QKr6dLKwWGD1a268LXAyot+NSb/SMJ9UG8Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:XDGRfojV8IAs++DF5+o4NbL7N5ycKnoWamnLSLJm0j5UmTEu4cyDnvaqtuW2+Kjq6DjoHBuqsFD3Z59hVe1wnhZUJy4ptPBpT50OwNkfharEOSjvoD2qWrTI05kiE8RXreCTX01R3qpwMBAPJb8FC+x/bx4ESfiDN2cdSAzWOiU=,iv:di/FhoweChnl/g/M92C0wgH0T1nX8dCGe9yxcnhZcJI=,tag:TQtxscWFDvP0BF2gMCAN6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
