kind: ENC[AES256_GCM,data:Kcx10j1c,iv:wJ+yrBezZCaDdco7qbG112Rmy6b+d2UaYPhl4T30BC0=,tag:sKIU8JyvcX0sv1AgGXtIKA==,type:str]
ansible_user: ENC[AES256_GCM,data:e2jY3Q==,iv:bNmzsK1MRv0awrot+UcquTNPkv6Kman3bmj/1V3DDNE=,tag:xleItFXdykLqkdXwthUdXQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SHvtBbI5ZB2M,iv:T5z4c7H3QHvsaQ2E55dzac5vOkvJgxfw9KQg6XULYi8=,tag:WpQ6Dm1dOMDglp15n1Fc7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMzlteUhHdFBYSEg3NXky
            MGNZWTRTWFpaZ1lLaDVCTDVyYnR3c3RTUTEwCkU5RWpJSHZhODFiWjdNL1RvVXFy
            MjNxTDh3aWRrdEFZOTNSbXJCcmdCK0EKLS0tIG02cThuV2VCQUhWUE05YjZzQThz
            dGw1SkJ1YVI1dk9zOGVpMmRSb1p3bTQKY60/5YHPFS510PPr2Fsv5RfNU26K4QXL
            EYWKQ1vu9E6F43wV+Hcr7DPYbaIxT1XdDD/ZJULQI+lvOnj4msci3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:vfPcgzBUdGcZvJ9jUlk9FekaLbZFeckVaoaZ8KWlQRFwR0MnoWNbsfjIyGLc+IZyxF1gV+I3HxYkeAQKMTUtay/EhsYE/n6KkJwqbNMjUWNsGJzHCOOOwJgJGIEGcqNXNtY5JsjuPUke2f8+HBqV7/5JN/EwTebexVkrJuMivaI=,iv:UwHu9XyLcQ4I/l+ZDDl8CCBbj+0Yo58r7Po/BhfikEk=,tag:pMWumxfcQJtVSxencvn23g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
