kind: ENC[AES256_GCM,data:FYWZsI++,iv:09BN93k5nPgWJLWp99x0IWzPV2RdCi2Vu4Q+wfsW7ck=,tag:x+XttcJfjRuqrjypxTIcPg==,type:str]
ansible_user: ENC[AES256_GCM,data:oY0Pjg==,iv:nNbrf+LC4CiRwATUFrGaMcydHZGzyt2hdJnBFE6QsZg=,tag:RCcMK2t15E8yUCyj7b1sDQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PaT9FZUB4XYp,iv:EHdnMONvRZry5Pz46f/3jySJrTQDBeVRH/pDpI2XyG0=,tag:2A3jgsDeFBT4n5pMkL5Y0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaER6cU96UjR3S0dBK3V5
            WFBjcy83cFNrUWN2UElUYlRCM1lxTXRWUEJVCk0zL21TL1dpQUZtZFN5SGd4QkJv
            a0pGOE9WckxvRnlBT0VTYitvYTBsUlEKLS0tIHNDZTRUZ2lBRmNDN3NKM3dFa2R0
            dWxvR0dDeDVERlMwM1Voc1ZJNWV2M2MKDVDSwb0moyYJW2exIZ5VbvTlJI5Owpz9
            dfFt5x6HDFbrKnRRaVApBNdBluwKqMlWRnXhN5ciXsuGWKqzUEPYSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:EQEIH6ko/h7hIDjh2GdpjN94itdvgLVvoOY+QmBxD4qyIvt6RE16NSg3yd6GLeuspnfkdcg3oOmZYT0XS1XtYUcocxYQYNHDiQYL37VWK+Hkg7sGgr8l3SCb+c84xi19q6Kei3ZhWNPIkHSj3Dl1qos/yRU+5Bd30FqKUVuab+Q=,iv:OMc5Lb0NwcbRm3xJYmCdsLMAaYzSke340wtiregbouk=,tag:DqTfWXdDUZxqwWhfVFOWWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
