kind: ENC[AES256_GCM,data:HbK0rJwy,iv:O55i+ZBabIQidrkY5XsuWBtdgxhDpwD5WIQjWN2bwE8=,tag:9t+ecxN9MI/sM+RNef0Xlg==,type:str]
ansible_user: ENC[AES256_GCM,data:8uwc8Q==,iv:p1UbmjBE1+0l/MRNVIv75bSk3YZ/o9PJRXsqTyndQuI=,tag:6+AJoYYrOWFNUUT+HIGoQw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dAOAwPOlYNFM,iv:E0TIBNA5Nmx8bjygX7FzyTIwQQgUEFi1pmeSJodo8ow=,tag:HZ0NB+ZmsxfwmOi0Ck9f6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTUVvQ0lqb3ZMMURQNXpn
            dmJVWU5VS0NNc1QxWURocjZlUzBxTUxkVmxBCnRNM3MyY1ArNFRqSjltS3RMUkhZ
            SVkxVmNnSVBLMjQvNFp5THh2QytjNGMKLS0tIHB1YWU3VnRzUDFLeCs3ZVBRbFFz
            YlJDZ2pBWUpTN2tieGVYS1ZBQStmeEkK5KNsBmQgu0I9f5Yw/UWvUUF6xAh6MktR
            iRc1a933sAvuxQe1jXn35rLQYT2cmxRvFSCZZRUObC41BgWJ2jXuRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:SMI9qXBgNHkkNvWLOu2yKhk9jfGl4T/L2nt+McKJA0TmYfF+wgVjzF/+SxxLFaDv403LwLTJUDO+P+QsGo8JAEvVDK9WyZxPIS1XSj7gsaoVlA5F1HHrmi6nGh88+ZEHKj761etHE03YVIlA+VsWwGDUeCYEEVZT4RrA0SLDLSM=,iv:UgJlKqYOPYRN/lDPnKLukiLw0u+4R4LCxk+7FFm9r+Y=,tag:uG1Tk5TnIF0BV/xmlxP/8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
