kind: ENC[AES256_GCM,data:eMeOIikk,iv:Hl3ZB08kjddp52AduMh+Dk2pCyeAAwBUopm9QZo5AFo=,tag:ZdfpKUQ7zMsaoklPWah1eg==,type:str]
ansible_user: ENC[AES256_GCM,data:PFIscg==,iv:QyDFLMidmatOxw0kp1aCa/aID1BbrnFR4EqGr0yR7po=,tag:6Hhd6gi9jXP9QHyhqo6R4Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:t9BCMf/FGVbd,iv:CCa2NJ/KWHx6rGjuR9sisUsK5dqpK6sadU9iZSFBGmA=,tag:GGgt1KX45oCL+8XlCdDiCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR0w3T0YyS0N2NjlqdWhm
            QWhpNjg3djluSkthK2tPem1Md2hoTU5rdnp3CjVIRGQ3VXpmY1BObFFQRVJvWGFh
            UUNIdWVteW9kNzJiWnN6MTlPS1hReUkKLS0tIEpsRm8zeU9VWnJzOTRKTHZ3TW51
            WWkrK2pGRW1wTkJRWXdUajJLVnBFNXMK+P1jMzZXu3A0Cpb3vTyv2LWGjzeAO2xH
            leknfTWYsM5Bg+egTGWNzBBYfGAvf2v9tN225FTYEj8BCCTJufmTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:DHUW76y8emSdH+me3Mz/lUNm70eIAQFUtKIDY/dD7QGb1cJpkmvfU+rNV5H1+E6qNPMkQSpORrqgVDhY+ZK07gwmN6LWG3DeF+ZSzT1bTSQeJ63qjbfuFN/FlsYS/z9dnBZ0M7aVIBuGTSFco3oKE/jPECttnIrhThXq7qqcf5U=,iv:QOMQCJPN+ybMIKHtkSvKcrEf4zqxqiM7lt92kFVoejQ=,tag:40TiO0CFgU+85IOFH8kCBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
