kind: ENC[AES256_GCM,data:8QCXbG/i,iv:XhFr6P7HV8Z5wPzKC3a8wfMQ0kZRIbHL9hrfaenk1TA=,tag:TccX4uO/eBjm0bsgNRu36g==,type:str]
ansible_user: ENC[AES256_GCM,data:Y6+VNQ==,iv:HwCMwtvwdMztvRTIQPFnV30A3afvRJBUJmDAiky476g=,tag:qE9KlomU5N7gbtitnocSpg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FXLEqkIm5IcK,iv:cqBgbrO1MEsKCfdtVVhSSsVVuu/JFWP+WC9LvanJ6dw=,tag:4ovTxxD+xAzx54s+e1biuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMDZHK0NvTEJmamoxcEtQ
            QUlaWXprQTNBT1BQb3M4eGFFMDQ1anlraGswCklSTFBuUm9naExIMzZCUEE5QlQz
            WVhNSWM4VlUvL3ljYzBqa1did2duSW8KLS0tIHA1dnBrNHZlWFlDN2I3aTBsUUdB
            d0Y1L3ZLd0I1dGttQmVNL3NnTkgwTzgK/ZPTa8u9vgl1DNEJ/5zLzJHy6FM+E6RP
            JGxrq/tGgYGAycjwImpvdcnxzEGhjpTda6HTH1StBEj+VJYzONAj4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:Gm0iIQI59Luj9QyIeYVmtAw6mb408uByc5cyNItBVH1yeD0Gx9awavOAD0QGG0oAOHfGbICajnJ1eCJ3TiZqjg4tMTq2JohWFVw+mb/3RLg4GoweeWIkSUXb5C2BF14L121BJruIi2W3mQ+yHQrGXjrfSYM/PR9765X+c843+Jo=,iv:0gSRkI+Y1XFhyA7O0znlCOgiwNzJuDBEfJMsQ5YMvpk=,tag:Z4APv1ZBGh9EOqm/yw4LMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
