kind: ENC[AES256_GCM,data:PrOW2bxx,iv:n7TgMICq3VxBHXnV2dC7dFNAmJihkExRF6NWuzLaZCY=,tag:umwq4JWnuSDT7OJS5e3zTw==,type:str]
ansible_user: ENC[AES256_GCM,data:yxJKYw==,iv:jcuvpljzRY39eLqfSVtfloppB0AoOGP1RFpT4RU+Udw=,tag:jKw6CpZEu3JYWqxBArVXsQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7Vqe6IdbT0aV,iv:bpS2ecL4GlGIXNXkfkzV9X6kOIbwpuTf81Y0UTx6MXA=,tag:gOOhatWTqXisj3lW/qRb2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUVdmTys5aHVMSENjcWVu
            VjBwd3B2dEQ4Vko2dFg1a0RrZFFNREtSRG4wCjMyMDhZSGlzSUY1N2YyOTJxd04w
            OWg2TE4wUVJvRk9rK2ZFdDltWW9ka0kKLS0tIDNIVDdzVUF0OW9kaFdFV2J4ckpp
            OUR1K3FyR2d0ckFZR0k2SDZSdlNlKzQKkY31Bfbzh8mmsDs1AlJxDxu0b/DISZXy
            eAis5jdpj+x9AcMeO/rHi8apV4f8tDw1JN1p28K2GdTQTU8OZsqNsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:b/6ppgi5yMEAEfQ2wBWgzF9RJLlTV9Om+t1ldX2yvn0NNfyv8QTBkKEI3I8kLwQOTx5LYYqBGwHp/kJNcGsjDG2SvAXSjbxeJiWdOrqAuYbXKXU2jZePN2dwfzdy4nMKTYToNDIMD9VE32B2PaM1cs7zp4od5Y4jACrfo2Qxpl4=,iv:W5QRXqY2d2wPDuo0OeDR6anMbuWwC+XB2hg/oImsZes=,tag:cmOEJqL5j5qY7GhH99XMPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
