kind: ENC[AES256_GCM,data:FXeEtPff,iv:4z7TYM3TvLjXqpJ95FfHS7YzNFT6pMUzqWUYvDj4nuA=,tag:MfrrX2DrLaB6izsdlC5QUQ==,type:str]
ansible_user: ENC[AES256_GCM,data:Vdqu1w==,iv:zXo82Y06TFARBVoBoE2Ul/Jnpu2l8A9JSbbDpltiHLg=,tag:Tq5R9vquLN2YVP5I3pxqGw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PoLlAkzzkHwB,iv:FSn5hBfQUJ5PNDXLpyxZDauACO3sAmVzHPbGXyGxcvo=,tag:0u1wzV5vtoiIU5jdmTODqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNWpkdEdIMk5uSWtwcGVS
            V1BhTHZXOGRWckYxV0hFY292ci9XR0VuekQwCklDY3IrUWYvK1c3RlhLRU5FOFRm
            TFpjeVlnVHY2N2piUmZ0MW0yaURvOVUKLS0tIDA2bVJab3p5VjN3T05YNGQxOUd2
            T0hxaVBWQ29veEoxblh2VDFDa0FUejQKFA0xcwgEIFUQ3tVDt8IVumji7FGkN35z
            EZ4HEnFxhYwfQLTIx2ZGGxidbICQzEPyYay+ESOTJyTLTffBnb7FtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:22:23Z"
    mac: ENC[AES256_GCM,data:3wr3QCv2uome4gP1kN8XvClXaLd+VgVWx0XDW8anmDdlIj3j+j1FmwZokCzeP78HKhZJJIwZkcvq+/WOFGR1ZScdPcs5pzevBWakJwi2UsFSSv7M1zMA4BXPgmNOkiGG+EWbGLNAcntmUVkp3I8dBMuTrr/53zoTsM8QL3CcWIw=,iv:h/Yst96brgm57EilBYv2AJHMx9Obi7CEC1NXFF14d2k=,tag:J1/+oHdK3fTc3WoT7wjOXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
