kind: ENC[AES256_GCM,data:f8jn4soe,iv:qPFytEc5w8M/YFX7Txdlx9kDMTws6OfFblWEZsvGKwA=,tag:MZR8412YAj9zBI8b5bk7SQ==,type:str]
ansible_user: ENC[AES256_GCM,data:3+iSFQ==,iv:2Fp8gDGTwC6jyESa55sn8z1uUi7XCq7pKxbj1K9c4U8=,tag:+R6TTXW6qg1xEkuu/xkJYw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nZTy65zpEDvr,iv:wOEZ1wTehQFL0GDUypOdMNvcq0fzCM761nDn4hg+rUo=,tag:gSk5tOhi8kz4qseVdpMv/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR29vZUxaZ1VCVDI3ektK
            Z3ZqYzhMY1dTY01qbDE0Z0twV09pTmVOZG5nCk55aXM3WFZtaG96UHZKOE8xRmdH
            QmVRM1pOR1lHVXgzSXEvSUNjWW1tbUUKLS0tIHVKbFM4SXhHdkRJb0U2dEdhYVZ4
            MmEyUHdVbTRGQkJ2RDUwTjcxUVFRQXcKL7ZXbnUNxbRCWKUo89DD+Rn7vU+i6cu1
            3ik+LvIH8A0izUPXiC2uBJ8zfYPSvDmn7DpaKHmjE640ju65YyKBcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:Qrhs5smNJinTSXal4J7Nw48vS1nXk8kK8Cqx2I4FsEXPcwZSN/lqIjP0z64/1s0mFJGAQZnyX7TUGCqCAjS5rQBZ9FltQ/9sp/eU2dA0s8xpsj9u6ArLtQByC9fIjwxUrj0rWV7yzWW+94+v4PAUvtcw6xKjL5I4WKaouNtlZoY=,iv:3FSnzPHvoyTywitFeOhUpwzQj6fTKy4CZ2t3WAH8uco=,tag:aZBAH07fIjP6qnyXy46w5w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
