kind: ENC[AES256_GCM,data:rEv5MRdT,iv:lTZTipAd8Tny0cSaVMATmB9VYRFbO14M56tn+zzWVEU=,tag:Wlaztiark/gEC52F3y1apA==,type:str]
ansible_user: ENC[AES256_GCM,data:dVoz2Q==,iv:0ftLCAwB8VIe2jGLdAFaulYcy0KgOTiSrxxh4YY0da4=,tag:u4Ki8fMijKt+eg9fZE7URQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wFnrFRUqdDyA,iv:5tCBBwOvo9zB7sH1/3eAY85L6uYLyCO3Cw3GuXQuqj0=,tag:yBexaUpjPIEIGHXj9dp7kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY2JraXhEcXJMejFGV2lV
            aXhCdmxRaHk5R1owTDlpamYwY0ozdWNiVXp3CjM4Q3RZSENtc2tKK2h2OVZKdFV5
            UUJnaCtmVFljSS9SSXEyeEtLNnhOZUkKLS0tIFp3TlJISERudVg5SmZZdFQ3SmEw
            SGNQTHNnYmpVOWpBOGl6bXdEeVU0RUkKE3/roqGDAV/IqqDas3KC56ogdHLxKYzR
            HL3/A9orjijn/ATFFnt+XJXZatmAvqCVQEL/EblsAOmaLThXfZettQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:PmDJ3Va4XoLKh/XQtK+MEK3lhBnPYtKvThD9ubF6e7xAUrKxHKTbifAL+frL29r8n6dtFjAqgugI8WyM1gQ6XWLdhnzEIrUiViYGldai3aoDNjXjI6voSkQLTx2KjgIPq+2tJf4xmQiCSkvFktIuDHPMV7o9X7i+8j2X5lO5Y+c=,iv:tZHt229tAQoAzhn/XolY7ebaoPRmigdY0SlFLVSupr8=,tag:vvzJZ+eQvrQIxiQpRDoKbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
