kind: ENC[AES256_GCM,data:o2Bve2Xr,iv:syupIDmOJr+yCUzrxttWZcQLrgAFAbTAA9a/ndkIrtM=,tag:RtQiOQVoZFV36ehsll4Y1w==,type:str]
ansible_user: ENC[AES256_GCM,data:4rPMUw==,iv:KErrCvOdxH0uZmNhpLLpOsiuxK/IcoaoxSbP9+RKLj0=,tag:onBIa9N0QITM6kFyqRC25Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:v0nwvrA2xa44,iv:0AI2f5xxIdZW5iiEgyc4jnJpZnDOLil4mt+Bm8XVe/U=,tag:goGJoNqvp8+0fVpKF4Z22A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUDdZTE5ybzRWSmVmQlZT
            LzJ6NVN2cHN5c2haNTRWVVdrNGpvU2I4V0hnClVvMlgvbTB0UjRnM1JkaXhDZ2ti
            c2dlZ2J4Z2Fwbm1MS1ZHS1NOZkhvdFEKLS0tIFluR2JZaEJObkpOOEtramoyRDVU
            N2xaL0xEMkVDYzNQY3A0TEh0anlnMUUKfsv8E3QyYQJ++ZfF0vYBlBbmtGxCCjKI
            EpuVwjvG/s6G/zSiCh4VHxD3+DyX+taJ5pzx4UjxW8RKz1oVTu7VKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:R4f2su7OL9VhDndeM/NFovxKCURV+rG1ZXWeb96xevYJdi8v/rMDrtKZSJgX9EVxNA6HJjyA6Dxx4FgpnHIcRhF1CIT4U2oWCa96aDwmcF0/KYKMyUX00OjkRIPP6XgmpFaQgBNwmzqB9PBklbyb/ez4u9y8CdR8wMVr7XZmlq8=,iv:5DUH+mqBmYXg+it2TLhES7zwOGZCriU4RxD6fRMWTCk=,tag:8jyxNq1aVOg4e053SZ8omw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
