kind: ENC[AES256_GCM,data:SAO7HPib,iv:sV3IHYNpFj+OkYUAuv7Po5ztrqrgTY0zgM/aX31dJ+4=,tag:a53GHJO0xRUzHNWqIjMQHg==,type:str]
ansible_user: ENC[AES256_GCM,data:s310zw==,iv:bHLN4nLuk7QrZhi4NM1lQ24FFRAD7vq1KsqyUwLSZ0w=,tag:UVUUxefcKqqRnsJWfPN5sQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:liI4junh83Y6,iv:nPi48WzMjO635aWNLriW3xwJL6F86GgJETo1zuoqS28=,tag:usM88CbLK/kis/CY1PNVlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTHdIczZ1TkF3Tk1EaS9G
            dnFJV0w2eUdDeWp3M1h6WW13Kzh0U0dqTmtJCnJEUDNUV1VNdUNPSXYzYzJMdHpj
            aVh2RjJ0VGRGalZaV0JhbkFVUEtFNkkKLS0tIDdSRVppT3JYTU0wbTdnSmRKbSt6
            eExmM2dZcXZBajU0TGR5SWgzZGhlcjAK86iXlFioME6KjRQlHx8NErntYMD6NPNi
            OgH6eyyI+GUjQlNNoC+JlpVwfACH+X8/3mge/DSC6Rkk8UZ/CG4GOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:hzutv8381ZyHjZGZN4fU8q5UF0L9CTj43h5YVtChMjDLOwdxsSg+2ulsMhzW3bvGOXu/m3vH0mkFUVmns5dgkg0K/m+jtrlgvP5E6xBwfLaJ/6zq2c67HPaQjTmB/sYCY33zfP/VVxtbhD3tYUUZKV4rOjEpb9327/8JA4Zbzf0=,iv:LwYT0FZK4MdeQZQG/VhPT9me0uT9EP8xgpoQZB75BfI=,tag:mRkvVcBdz9KGRQ8CvZfiAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
