apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:8h0gif+B7S9fEU4AQ0fmEju1yz8HJ8ucHvbe+g7s6XxUzwEc,iv:qv8/QdglQEAeJvr83ySZo/2+FlwRs6Mv0TuND3lAPxE=,tag:I3ijrjIEP/TRxL19AleugQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:ISJL3RLymGs0TKi/MqIc6jclx9cl/1EfobdtuwS+QfjGnk42b7CL0uUFM2+Biq6K2Vo2BZSvqSXaQNRUtF2L4xTEfcfcTbkZnEtpJuWztjtQZpOMuF6aXPgsOA5E6Y3oPBvmP3yjYLVZCtZE/ycR3pZlW1Kv46qKinz+bBUzKIDS1GkAM4bObMaKuME1Qk0bgKQRI1NBoha5udoZnKmWIIYHNvyElIX8eqX+IUnHPQ==,iv:7528q+0P14wfgIK9qJ4PiH+78+fEGnVVUhuMuXKJhdc=,tag:UnF13RIvYdMJfXFD+gBJcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOG5ZcGNZZjhUZERpSkhV
            ZWRENDJselVRVHpycm9LaGJBNlFCTGM1a2tFClllQ2VIa0hSQkc1NHdOQ3JPVHV5
            OUpnTTZxVEk5SU5MWFZRMnE5cVBKSmcKLS0tIEkxelJPNmtGVXYwUkNtVWtJQklk
            OFprTGZTaFZ2SHBjb01odDlCeVc2U2MKfPw11cGjItPFzpPnQ3STghuLS0RoL14L
            2N42CuC4HTWZdG2YIOwSFH1OyxOaSNWoWvxXQ3qd4B1FzbaQ8UvStQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:DA6tKo+vwpMXql5ZXoS1D6DIxAFNK/5zuoKccxIxA/Lxh3h6BsHOe4XRhsTNOGfSLM8u3KNzDad9k3souCyQ5GY1tPwfg3qJ/0rzlE7Lejxb8yDAFv+LlthTrrPOhLtjiNFeirBn6i1zqjlVVV5sUl+ABXWG+Csc19bOkiyRPWI=,iv:5GiuFhKIC4TzidjhJ2JYjL5jDAxsqas0Lx8L1bj39e8=,tag:rondZq9eKiwJ1hGJVGspzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
