apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WW6hpQbelZUrNOVf2xqtpuM7noNThDrr1VJuFj2/zZByXlHQ,iv:jsSWH2iJC5f66yoAHQsZFgD3+oWKmacuMBku7f0upe8=,tag:AseVVTIjVsPXe2q4JkOI8A==,type:str]
    credentials.json: ENC[AES256_GCM,data:HZg9CPbhaXdMq+iM4pp/Q4jBr8NhDgsAuL28b08yTRylNK5gnLB6eCuJV+DyHnkBgM9KN851FntElB5zQZAbmP1YYqUt6J8dwxInlh7ypVK59+P4gf/cIVFASrMiGoSeMwF0VjQDbA9M6D+sHfZwYO4CmElR5lkcmvLnwyHAaikxMPscRwU4lBQpeTBwI9Gdo3zGY820pHUH3xPXxMKh+Y90SfIgC8fB6iw4VHX1tQ==,iv:GDL/nIe9MkzFQQ2vHHbv7qiVv5nPuNAgaXDH9Z1IUf4=,tag:qTzzMnLrk+Q2Z5fhiYsU4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU1NhSXg4WkRrK21rdDlJ
            SVp4NXo2OTZFN2h4L01DU1FvWEVBSGlJSFVzCnFPakpscmZZWDFKb29lZWdXeWs2
            alJmQU1oVldDTTlBTGtzNUNmZTQwVWMKLS0tIDN6aTZwbXd0ck9VVHN6UDNMSW5Q
            SzZuc3ByNURvNUNRVVpia2h3ZXFNZHcKgSUXJMkj9krRv3eu3TxG5qwWQDfhFHQK
            X47LuD2ZFvhJCPbPQCLVnNX57zMGRmfB+NmAEgh1Z3SboDk6I3HeQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T12:11:19Z"
    mac: ENC[AES256_GCM,data:ZJj0yohUDqi2cuUU4lUhASK8OBJcvpZ8euwYZBfvMq+5yjsPz27XlvgIZjn6PvB+XkuW+52lQcO0oJ2q5lJZL+DBqHN9ux0gvegVTRUvnqLKZJlTnFigm+sLkAnInXM9Ln7opAn7MMRcXA6NSySNLdVK9xkEumGFR9fTg9EkhT4=,iv:8OJJnekIiaNTqe8Nko4p/2ufDEtBG6/DVmD6tqrx4Ms=,tag:WgErcoGjuFr9RIodvBQ23A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
