apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:BKOwX0dVdO+RYW03AECGfX8owAML8VSEcNPIdLP8ylv8vYZ7,iv:/Z1DEdXhmsnv8UF2uNz3JivJddfyJ8lz40YBcQ27gdo=,tag:4vhVAuSXYtWS8XNSkpr54w==,type:str]
    credentials.json: ENC[AES256_GCM,data:+7MUEAsOOE8qqm53LbT+2rG9ES5ALPnKiP6jm6XqD9N7wrYpuXyv3DqszzfGGqTbPsQdl5233IhJVLg2Mk8ndTkM6NWbSCdx7o4qpFDZF8mXKAcsT3qebVXxB5K4lKKFBgCOax7gXypdcI/IHuWg3Lfg1gBKyuL62Sqghwjed5UNXuMZgkz58IFLGIHLsUgvj9WV7u5A6hujnfeWpcnOXBVmiE0ZbiaDwaZKWdWHdg==,iv:vxWg00ZFZ4vt9l9dQCXECo8xI08NXMjeqYQVyTXySp8=,tag:O6Saj+JLg9GdImHnw/YwUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOUhlMXlYa2pUKzFVR1hi
            bVZ6ZUQ3dGtxWFA4dTA3elF4dndBV2FyVGtBClRUd29ER2hrUjB2dHVIc0g5Yy9n
            SGpQSWdBSDgxT2hMNk1hNnp6UVVQdkkKLS0tIDlYcy9iN1Y0MS95NXlDZWJBQnI1
            d3hlaHRsK1gxbkZaZlZJdURqdXhmZ0EKO8JH1HP51+jUQ02LIXm+vRj3rHvBgtFC
            xqUS/BoUQeevfRw3Gkna4UHbZ7DE8rKwmVgqVBTPkL8FaDqO5XeOKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T18:12:29Z"
    mac: ENC[AES256_GCM,data:4h6GZCwxEoXYWusCJnBL0HlOdSR3UTl64sxrWGLQgrOscCOpr8PZeY5OHmj226UTU6gjKDt5pXRTSLs2pyL+vGTPjSSlXI7863xa5EIVDokCOi4NsXW3CoFadDKefxxjbzhYkab412IDqnKt1aLZzS9oRWd8wGATC6QmeHkpwcA=,iv:v6fMpYL1CyYSZgF4WG31ALP/MpQnmLlXbvRFMkJqx4I=,tag:Johr8nyfUX+Nzm6yfV1oWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
