apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ABCGb1qMY3ZbCyiL8TuBYxgxsWEHP3Tp2wTfaIv3fJ5nOoOq+bTaVQ==,iv:kcXElgST+m2sYY3nz5IaoGVKpOemD2I4gOsad3NvqXM=,tag:e2cmyrqd0arhqs8tb/4lEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTmtaNHo2cUNtQ2E1QjJM
            UmFtenRXMGxSRUdoeW5DdDM5aUJxZmNWK1FZCkVkcEcxMWxnNkd1S0N6WWNhb201
            cHhKUnVVQU0vVWFEUE41Qy9XNVNiQlEKLS0tIHcwbEpVelZuRVVVYTI2R0R2YUps
            a2VlZ1UzZCtTM3J1eDB3bHo1aFlKY1UK/jkJ2Q8FF8xFTy+cyx+IlIsTqNzWtfZ/
            gh+TeOar6M9ytSmghZhOHmgXysjGb88wqqwn+8ATq52WUllKUbleNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T22:46:48Z"
    mac: ENC[AES256_GCM,data:E9kwKR50VzdwEewHcUai+qqSlb5mlD/cNMOInvlPIXTBPQ+Ky89x5xlkEYzh2sUrGEAckj7MKvjnD4HTtNe35M9s9sfbEshIVUG7qoXSp8/G2dsOuJ9niW+OCfUlu2wQd6Pb2SbsIg4yVpKrS3QviLbKtsIl7wfqpJyitDiOYDY=,iv:JPfG7Ha6N5ImhA2tuJiI8c3vbeU0jzXvkXvpbueddDQ=,tag:oue9o62fOMtH2k4NHtUAXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
