apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:njcnNYhCV2ooJKtRZXEAG3Z/M5Jfoqpx,iv:XQt3eGgmQU+7egcI0cuWxnVBZ5mIqi1zc7IWXbTsgtM=,tag:ERXby7ZQ51b0MDEOmz4ykA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OFNrc3owY0hlS2M5TE8r
            d1FzSjQ1clhoUVUxMEtkMWY0eXBqeEtPMmlJClJpWFczZnlWdDlCT1VvOUZtTXlo
            QjRhTExHWXlzWExaMmdUT283aWtMMzQKLS0tIDJtOWh1d1hPQmZPTHVsQ3ZBT0NL
            NUhkWURZdjBqeFdLS205R1o0bzlyK0kK4WZ1r7ynGbPO8/nPNPWf2GnNDz3Taik+
            iZpJXQl1YdfzQjbsxc1aRDOFhX7kKSybvTTFRqFv5nm42hcwAKlKag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:ON+HMzrmU7IwcYpY/R+mq0uzODSIM3Q111cHRWyPr96M/c/4srWLeaDDFuumQyXjptPVymRN/A/nAI2Wyg0wKrR3/HjfgoWTutm2HPyv2Doar7UKo2nnAnREf7ZJzJ1javsBUG3zEewReYZ8/FotMwvHYx5S3x+zZy+hTRdqqgE=,iv:Q5lXUcF/C9gWgiC+CGe6/y0b52fBxW8eOUGEwuGCiEc=,tag:F4mSUJGN5vhc8uIx6guDVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
