apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:r4IoG9cU8G7DnD/0vJ+5CVzDpS99N9HoWQvYf6209/zs1IFcag==,iv:a74PyrDPgWg8MFODoaAZ0XF374GWCiyS0FxgB0khvOU=,tag:QB1tx9CNpqwquEFsbXM4NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNkxndDhCMW1Wb1lxTTA5
            TDFKSzZ6c1A1bkJhZW9jd0dTaWpRZmVmUG5rCmU3OWlzRDJVZmp5TGpDTElFdFhw
            QmxaTHZnZ0RpZmJTaWUzVktucVNEdFkKLS0tIG03QzJ0QnlMRnR1VWVXMVJDd0ha
            c3hoTFFvRzlvbGRhMjhRZVl5N1dSNmMK2p98j7EMYPVsj6ua0YYvQFKa5XYGo2cU
            8+apv081YGjtINS47aMVXKhXCmZAuuiktWd+zPSd+Hf7gr4bg5z8fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:22:23Z"
    mac: ENC[AES256_GCM,data:NaoFpRrZ/SDXuQt2d4SOGzFR+Olm+moRUKg3VtixberPVK5u7EYwEU7SfToDiwIxjBsz4NkGreoTWesnf6ZEv52R4jd5rDHEIGEO/2ia5nv8zS5EyYOo+AXdvB4ZY/ZPNjxPQPeawTzchou7dilv24jfy33ONZYHqJQSV542d08=,iv:KkEwvO8dWlFGRd4wYSSEgrPuNAOzXTx7mF631ErQHCo=,tag:+s+YvZG+gMLCDszl9JXVcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
