apiVersion: v1
kind: Secret
metadata:
    name: emqx-config
    namespace: default
stringData:
    admin_password: 6PrQ@N9SkN@&52aq^rRrdpXw
    user_1_username: Epidermal3710
    user_1_password: 6PrQ@N9SkN@&52aq^rRrdpXw
