apiVersion: v1
kind: Secret
metadata:
    name: emqx-config
    namespace: default
stringData:
    admin_password: ENC[AES256_GCM,data:RtErZXzdvOvNObaE8QkoQN/ae9FDKMCq,iv:xoM+96mfnJl8hGtzUlk1Fej7BZgAzA9kX9idyAlc6QE=,tag:ZWsSbihqg1vtMvj3GGa+Uw==,type:str]
    user_1_username: ENC[AES256_GCM,data:m441uGQq4jh9,iv:juo8taMG816BakhUajugEkZYxABLbB8sNd5GtmrXwV8=,tag:ZeJAQEW1cfBlnZLdlekwPQ==,type:str]
    user_1_password: ENC[AES256_GCM,data:oXRUrPnLPiQB7ixMgBGommdSJpT8vaGj,iv:cSYMjgfPJNKnK99ZBeqaIbOCR8u0Lm7x8FpfW47lLCA=,tag:Aq1Jnq83d0RcuJ6zd2+xoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS21PRCtMYkhVSWs0Zml3
            NUJleElCMThGWDlGc1BmZ2pHOTA1dEI5alVnCjhRd3VGQ0ozNVhjWEsrQnlod21x
            bkhPa0tFNFZhWVpKVE9vSG1FSUI1ckkKLS0tIFhtZUlHaFFOUTBCQzZOdmdWbklj
            TG9UYkdKbE1PMkZJb3c2TFU4VHBhamMKML5StgXbdCkXwUwIffUE4SnjSdKSUokU
            mrYsL+xxvv3lNL9WDTJhUlPqK/b+OQI0KnVziZrfQrTbuW3Wi150QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-23T19:16:36Z"
    mac: ENC[AES256_GCM,data:vFyqxNGEMivIjm4hdL1lDzEFHBovH+mwF4nDA60r1Mi45sn2X6mbjYNBbhITd5KeN/WtfudA9IGT9puwBhjemJHs3WYmOzGfiUkDGawM+2+SbslmZYrgSFjcDmsCMom3O4vXmKjd6oR8tMg6HRTsJFtFDE97qm5GZFGWNTn0Iwc=,iv:iH243MmwkyrfD+EGMA9F439Ugs6hRxgXK64D5SFJEME=,tag:d1NXiCQ3fYJI5yBxZ96JHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
