---
kubernetes:
  children:
    master:
      hosts:
        k8s-3:
          ansible_host: 192.168.101.13
        k8s-4:
          ansible_host: 192.168.101.14
        k8s-5:
          ansible_host: 192.168.101.15
    worker:
      hosts:
        k8s-0:
          ansible_host: 192.168.101.10
          rook_block_device: "/dev/disk/by-id/nvme-INTEL_SSDPEKNU010TZ_PHKA1523032W1P0B"
        k8s-1:
          ansible_host: 192.168.101.11
          rook_block_device: "/dev/disk/by-id/nvme-INTEL_SSDPEKNU010TZ_PHKA14740ACB1P0B"
        k8s-2:
          ansible_host: 192.168.101.12
          rook_block_device: "/dev/disk/by-id/nvme-INTEL_SSDPEKNU010TZ_PHKA151607ZQ1P0B"
