---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app factorio-vanilla
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      factorio-vanilla:
        type: statefulset
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: factoriotools/factorio
              tag: stable@sha256:1f276f39213c1c8be66dabbf6a21fe9d47326c5b600acadc30fcd563fa0f0650
            env:
              PORT: &port 34197
              RCON_PORT: &rcon 27015
              SAVE_NAME: "vanilla"
              LOAD_LATEST_SAVE: false

        initContainers:
          copy-configmap:
            image: 
              repository: busybox
              tag: stable@sha256:82742949a3709938cbeb9cec79f5eaf3e48b255389f2dcedf2de29ef96fd841c
            command:
              - "sh"
              - "-c"
              - "cp -r -f /helmconfig/* /factorio/*"

            # securityContext:
            #   runAsUser: 568
            #   runAsGroup: 568
            #   fsGroup: 568
            #   fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        controller: *app
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          server:
            enabled: true
            port: *port
            protocol: UDP
          rcon:
            enabled: true
            primary: true
            port: *rcon
            protocol: TCP
  
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: factorio-vanilla-config-v1
        globalMounts:
          - path: /factorio
      helmconfig:
        enabled: true
        type: nfs
        server: ${NAS_IP}
        path: /zpool-mirror/backups/games/factorio
        globalMounts:
          - path: /helmconfig
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    resources:
      requests:
        cpu: 15m
        memory: 1555M
      limits:
        memory: 8006M