---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-vanilla-config-v1
  namespace: games
  labels:
    app.kubernetes.io/name: factorio-vanilla
    app.kubernetes.io/instance: factorio-vanilla
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block