apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: downloads-gateway
stringData:
    VPN_SERVER_ADDRESSES: ENC[AES256_GCM,data:VmVte2R0agGi2u6yEZaGV792StHzjXWEB2kRgHkPOtP2PwnKs7ax2vCwKliyRMo=,iv:bBtIebJFnNq+0HBYUak3aEp4cFFsSprIXABuXSzP558=,tag:+UllPniE8/jRKENaH/nd/A==,type:str]
    VPN_WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gy2xE8jvsDvoOavo1DCiYyRUQagoQfZAST0dQrJySgUHJ/cPQD4LeKb+VdI=,iv:rTitiShANSKPFJa8PyBt7mrteGLa5bx8IT3HSCLCuVM=,tag:AqU2LjG5OzR5PyPpuOHZcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbk0xQTJ0dUtaWjNOMEYv
            UXptNmVQM2wra0ZIZERybHNwUy9YRW9zOXkwCm9RckIwMUZRK1dyVWJpSHNDMnFi
            K0VJZkVxTEdDSzdlV2hqVkRndEFwWDgKLS0tIGZyRXY0ZVRWQ0t2Tk5DbjM5ekxY
            Z2EwTGFOOFVxUFBpQUZaK0xzM2pxMU0KiNJPGK8t0d7mhv18RyuvIjAVCU2KrvjW
            CjnVQZhEvVJ2mPUwY8rT5KMGCkuMx7twNq4fCxnTltmsM93L3fNRxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T15:16:01Z"
    mac: ENC[AES256_GCM,data:1a6GN3QurnDqSI1sps6007TM5y0/ffoNYtN8ujtb0U5HBWTNtgIovK19jCLsX6WpKnhnkpaFWulSGj/d2TuOPROQ9pDq8pOmaPJmEeUMKxCG9ypGCrOuLdHEGXGQwdXyoZuEbVysi/kPqIZeqHw5FgWpszysXPc44zS5j+McaD8=,iv:IbcUYKtLlD09HDig4avzhFySBSDhvWztwtj/mGspg18=,tag:5BRxtC43NEbO/z4uYIr3mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
