apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:no1IWYE=,iv:QP3Bs0i+CgunuhJDIzR3FhK0Spm8hSL+xXmL5XHsYz0=,tag:GxIu+U5n3m3+fjYe0ghB+Q==,type:str]
    admin-password: ENC[AES256_GCM,data:XSFfJ1vt29Vy,iv:KKh4Z0AFvgKDry2Vg1D+9rqNI0R+AuLXC+fL48V7SZY=,tag:hnmnbfEFPCNrl7mR0qHBOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUVJFRWlOd3NrRDlPL1BJ
            WVFsT1ZZVnRaeFVlK3Q4SDg4V2JzR2I2bjNFCktjWDRaV1h1UHU4aGZvblBhSWl2
            NWFodFNDNGNXTGVnVWplZGhtUG1sVUEKLS0tIElrK3o3Tzlsc3FFTzJmZEx5MWZ6
            Q1ZwRkpPbUpTamRSakdZQmRLVUIrT3MKk0NwerRvRCT07l2WA8pl5mMAbsOZFC2s
            yAO83pelnnevz8nzxbWVyd8u44Bk9BhTWUkJvtOe5ghTLQB4Dklj+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:AkS9NrSy2aS9cmIh7aJw6pbq7dW5O05kcJ8cqeG8Yl8TKsyyMXO2AhCPvou+WKTspURPzgzvz0XjblknhQ4vJ+Wc41zn7NwUXijvYu9I0p4yv6pGEa6alOwoglgarSIMPy7JpTHM/yhjQ0esdJU3B2H/YIKRyi7fZ2FftJDrdU8=,iv:a4gOJb57hojtegRaP5d+l1fs7P/h2p4v5Qw+Fj731ys=,tag:FDFT6KoQ2cFcah685H6KSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
