apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:gVOwD5zwUHy1viwhTbUr/DLk3u8WdvO41Csvtq63eS3nNIpS+g0C0A==,iv:eHTUxkwVxDB/vYHrghLTAjI2zQMY6jUNq5mdp4wHeJg=,tag:KavyrKUtrTTjtdZfQYRLLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac3NwTzZPNVJIWXMxZnox
            UWpscm1sd0I2YkVWbWJiWGxGTEFGdkh1WHdrCnVLVDRjalcycit6MkNwYXRNYnFK
            YVNTaklVTDBjb2JXTklFRUQ2VnpjVDgKLS0tIFc1NkdncnF2ZzJGdW02L1lTWDlO
            VFVPL01TOURIeGpXQkxuMVNoRnoyLzQKdbG4A2URQ+c3p6xYDR0tYkGKzZpIRizC
            HFc38fkumCxp5lkljAKEq/vlXCoktrQ+LGRCfExSJAJgUXYzeA0D7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T01:42:00Z"
    mac: ENC[AES256_GCM,data:OVHo9i9ZN76VztG6zSUGZvk7/8uxhRFFRDR0h/T8b/ttyrqapDhCnKyYw3KA43spE11/DAl1y9uMnHyOcjgLfB1F0ejx6U9Bb7r2lHWuub7oQ+jHdhz9RiC61gR+73NUlkH0ogzJ+Wfo3eZfViEdQvh+gLKhzRyrcPevCnbKW4Y=,iv:OmsFcZwYU+TG5ZYsEqDw8ec/EqjLAfKrbhT8x6ZPWBM=,tag:EHD9OcsvIj9Mo/DF+XOZ9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
