apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:5jY5JtLww4VKozkc++6v1eGGaFWV7wfziVVFJnU3Vl7rE6SDRg==,iv:1UnRFG2fY15STe58jaNcem8bpU4X0SyjBFjYSiN0We8=,tag:l9hnfQSD43e9I2CtPdSaeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeTdVK2h4d1VHcGVQQnhq
            ZUhYbU94RWJhNmR2Y292V0pBOWNLeXVSK2prCk93MXc2RXZKSmNDVWptQ0c4OGVF
            RWRORHErNk9BTElWdVQxK0NmdkVRRm8KLS0tIER5aElvYlBDWXgxWUhwc25RYytC
            eFBrOHo0azNtV1psTlJtVmNZUW5PbWcKw+YeRjIIGff5LouNhDUuz2O3hpm2H4OC
            +qptZ8BMLLVjJPnGuw0POtcsmOFUsS8DWX5KZyYBOZo0awCoWflWSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:5XU7mYv6PlsV+4uLxZ436izlmF7E+deYuUCrwf2yPsFVzM4inAfA5NMke6AiBI/xOwqdZwYhIGR2ae8dlpQZB7EggfXlxjKant9x0G93OvsaX1cKWSUb4XnMep3+S6Vw6lBd94zo44AiYoj+6gB+T8QLS2gQWa18eokCJ7sEJLo=,iv:SqITVZfJZnhWTxjsqiQTHhv+Sw5Hj/0ziLgGnf0tDXQ=,tag:Z0QG/HCrBbJjJRt6CSkJDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
