apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:xREqgmw5X2F6pyGcf7rGBZ+5ECHBGwN7DP6hsdzIE/c/gM1QMw0Xsg==,iv:2UCal/eVvSvrBGfOizwIyXmKXAcHhRYsrbrxMIcX41Q=,tag:cArA6bFSfpNP1geR2fyGFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMmphQWNqb25NMTErd1pI
            QXNXeU45UENIeGtTc0Fyc0RlT3JjMEJyWVZzCjlOdUhDdkREbVJLZWtOblN0MFpJ
            SUtNM3pmQVRXRnpVNFZwVXpSTlRqcDQKLS0tIEtVMXpCSkxCeXRMbWdRUW83UnZT
            WTlvdU1ReDBUWGNCZGRZRysycGRvNjgKWxvMCLBCRy5r2atw6UYsAQf+yazaIS5H
            nV61DrMSXsUHwJVAgjxKBDtq0iHJj9A0Buf4DUuaBD7cLdVPNYBPFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T18:08:24Z"
    mac: ENC[AES256_GCM,data:GqiQDappr4PFTLt7fPYtd/x06wjwNSOBimlsoEP9Ot7khale9pRyguaA2aiYKuZu71QjSwnkxN0VCPQnjg5Lir9P6p8AcDkueTWslhdqf7mu9gatEhipKmg1FTudvsToywGjk2KA1AcCdGBlzkvGzmK36bodxhJFi9QnuXBT5/w=,iv:BCGoAbpqiJmGA6CHRea2JRhOqQTNZ0BBoBnO54IWOLw=,tag:w2pL87paqG7B0sPj7isOSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
