apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:3bTzuZcUb3pDTu2Vefgzmx/u2U0T2+HEJyCz2u2W8J0FTeWcAw==,iv:i8Ftx20zw294GB9VusWubgDD4vECKBXtWHZbMfvEO0E=,tag:H5MqBLyEmsjpV+sZX1+ivA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT3pBVTFVRmVNMVByYXho
            NnZxOWNrb1RKUFBNQ1lyUE5ET1dnblVRWmswCmR4NkFWTHozM0x1eS9JRnJwdUYy
            K3RDcXVkQ1hqNVJSdGFWQnZQWkQ0VEkKLS0tIHdMVzlLNUEzeTYvb0xuODhibHRp
            djNKSEFZQ01PMWJNdkNBOGxmcS9nbXcKG2iI+ox4wMo+8oAmh3X965xhZ2vX6ZC8
            45ybZXW8RrgR1S/KUNnh4BLLdx/oLUIyPxEbqJYuL8Z0RBxT4hw/Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:22:23Z"
    mac: ENC[AES256_GCM,data:mI1Y6ctE5wVrSgxX/PMo3n5mGsjtxbtT9Dlam3asPmokLoO4gar7BUJP0owHm1Gm08/ucX1sdD1+cRD2HMnzCu9ZlQS5x4BoHHKXDlXn7e7T7ZN+vSiTJsqzAsrFn7GiHiOXrjP+Vg+mq0jKzuNIXEbISgL9j6/Jg2Beqlol1R4=,iv:41CKBOn4VG5s1f6UyuUydaOr8FcUz9KttxUGW+7pbkU=,tag:1Jf7zbuBubKNbvVsn6cATg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
