apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:QlQfFe+pfPQUryZ7WmC2dOI6P3SfcHwCwq8ooiQBM/PB9AMz9Q==,iv:WkRilxHSYS8BRweo+lPdE/2JXZqSUQ5t13owlJf6id0=,tag:6+4Ru7ueGYWhmipuN+Kpww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMHpnVjBuZEFTQURUM3JY
            SU5ib0pVVGU1OFZqdEtZbW41OWpQb1NIbkZrCk9Ya0hTTk9JYnRZZG5oQ2srUzgv
            WG9SbjNjcTRtUVJYcFljcEgydU5jOGcKLS0tIFVIRHRPaENUeUptVUhxOCt3aUNi
            YUlHcHVzSmkyTjFhN3drbHdpUWVMTE0KGO8ZhrpFPwWKiMO+bJofHq3sfq5gVzVy
            ULM+5ok6UsFWUrdnTsNYH6+QYYuLU+plRIRWlIZgJbMcAntB5CcAWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:5d94NZxIXOMXLWM1fjaxWwCy5tkAxZod/+igiDiH3HpxHH3jBzMwWbI/8Gz2tO9qkBMMjDfxs50Wm8+hHnxfaCIbQUep1vLpzLtZDi0OnPKsdjiYj8N0Du87rKeGQrtbM/lhbElGJxak3JM72BaQ+HO2/lV/zT9MScy1X8WESdY=,iv:W0MIVP3qfeYv7+8zwNIlJy2dOW3+uwUaLvmtRAzVeuk=,tag:gs6Deth9uk3k5pyVF0RCxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
