apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:vopV7QH6DUh/b7j8yfloug==,iv:nusUwLoFgjvrx8k87BVw38fjB5QXYJ+8srG9HaYOHgo=,tag:UBmViQoYvR6ppIQFVmFf4g==,type:str]
    api-key: ENC[AES256_GCM,data:l5WkUXKN1ySuIZeIZ4NCR0nXuLuGUu1n1yFtGlmAOxfmW9fOwg==,iv:hp/2dnXttygsutrJ9YFCd29eyBcrmb6JAkNntvZI0YQ=,tag:z8T5TqWjMRe6SgJEWn/Xdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdUw3cGgwL2RGbDFEejdH
            NWtCVXRKZS9YSXFYSzYrTGN5WEJFNVllbUM0ClFIeHMvazZXWUZGaHBORWIzbmNr
            RmZWVUdxOXVZOGFWclJSTlY0UTEwWDAKLS0tIDJwREpQY2Q0SS9rMGJnQ0Fqa1ZE
            bFNMbjUvQ3BHR1F6OHBGSGhwb0p6emMKr7o2vKAvEUyuDlhnWyD3Fk+lSuKyyCxk
            71z4UxOEYUQJrFARUOeuqmdYDnEeQlkaOtrePwUH9zOr9wwjAxQNXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T22:46:48Z"
    mac: ENC[AES256_GCM,data:E6lQJLtjArZf+Ust7nuOIHkfjEm8XuLd9bKAh0ldw0KO820roYktOlD7m3XmiWQ8pebk0y/pmGpPw8Djf2wQg8wvPnJcgex55AuKIqZBEZhkxDMoNyDJU12EqvsnnVnpYDzD/1ItMvhkvdNhHKDtEjEOwOIANp+gDkwffYjFXGU=,iv:c1jPxb6A949pmhosENokVSBly7W+RViDsoXNXyZExYI=,tag:5qCkLvTx1KxGrd9hIinIDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
