apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:OulWJL6RYss/HAF+n0A4iA==,iv:9O5GDOKPwW0kiCgYlMKOuTrs/4gqAFRrKt0/psUTFP0=,tag:bB+sG3+Djb/XwJi/yx3d1A==,type:str]
    api-key: ENC[AES256_GCM,data:WvEWrsU0zQmqHBxzw/dydOOLfQs5D6JsRxb5/xAh6eQFVEkhcQ==,iv:kggfFq5v2u6E9umFoErT4YEVbE2ypMLmqqaYf7PrsHw=,tag:8HLxqlXrzMWYLYJDze5PgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSFZqeHFBOVhlS0E1eFZs
            ejFmVFE4bmw5cys4UFJiR3VUN09OelE5T3pVCitidm4yMHlPb3ZpdmxxK2psM0Rm
            bit6S20yclBsMms1MVIzdGVDQmZkU2sKLS0tIDNRdTRMcEQzN1psSEp2UnBjRXgw
            WHV5VVBHdnVjWFRidlRKa2F5YlR6VEEKhrFPU4OCXVTbaIu7aKUYc26pmJJt6hta
            9b+ZZK4l/ZJmdNvIAQsWH0Hvhn8C31zHzjYp3IAgmH1MaCsEOc1anQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:GvLMACZUgQSYVVot6+bDQQaMA3c1srpVSOMlSvVQ3leWvhJ0VgknJYxwIYOcr7QN2Bsz0YZ6ODFrgf9VQt5ZcPu5QyRaNhARsyh78xG07/aDYfxBLIehisrLGALRFM1wLbACbvHQ1h7s/1bpFaHqL4HwOC3EcW7r7V4Qze9OI6A=,iv:/ZPrpMxlJByxy273N/6omcE/wD0uJEMuFvl7yUWLP5U=,tag:ondD02ANAqcj1jLOzjndEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
