apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:xS/l8uXpF4GjHrzBlLsgdA==,iv:1ge8OiUFZqfcd9MLzXB9PROzuGXnSidIJYDZpRbc7xY=,tag:keAtgFw8jryNHuf63onsdQ==,type:str]
    api-key: ENC[AES256_GCM,data:KbwcCdlDrCfBuB1GOOOnKCmcBNZ0YGnhzADjsh0t8OXJ6GxBBw==,iv:BduD9pwd510pSowidl/JNaxrAZtu3/4/NvvcKqdU4jo=,tag:VkQlIzv/eHzPyugssnr82g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RVZ0ZElHQy9USFRwL0FF
            SGlqMjZQSWhhdWw5S2liMW5OalQ2UDZHN0cwCjBnUXpXWXZtQ0o1QUU1Znh0Skxx
            M0Y0UFJIcEZ0TytmdWpkUHFvSURPWE0KLS0tIFVZV1lnTHRDcG42NWpaRGFQWWRD
            L1pPNlg0MkwybFRNWTV5YURTMjBlOHcKso6dNm7nCryz9XxRLU+jiarA9gcdlS7S
            xzQi9LOWg1AGpbLlPEdyEEGKNVL4sqfmHoyoifCI7EvV4Xi3jnHZiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:7XTPLQYxYS39M8FIt4WVSm8fUmcXGAOxRYOXm2kBzip3FofNFqeZbvmqXtrzlg1/OmDUaz93hQaQyeSmQWbIfqM55Loa4FTbLvm6CwjnJRa6x3Y5l8nQxRIrX6DV9kFeza+HoCBaNA9+16/KLKhizofmgw+dzbXeEHceGa4srxw=,iv:/2lADIT1vifJoZKX4kNdDix5XRjHYc5dg+7vgCeIEuw=,tag:i7l3R5fdkZ1dZH7D+VvPjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
