apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    #ENC[AES256_GCM,data:BNDgvLUV2PE7oxNmNUd9DzvI1XtRaoE2gLyseDAZ8zfZrWRjPr9QvIduF6QU,iv:/dsOlZzPe9/l0SqNJHsskSQRZWdxMq6jTYqwis0g+QM=,tag:jJdX7zv5PSkRiq7tmSLJFw==,type:comment]
    PROWLARR__POSTGRES_HOST: ENC[AES256_GCM,data:b+HA4ENUDq67B0hM/Oi4JCJCSKUhxzJxlMYtT3tVFKoWXCsKhglfWA==,iv:ZK6Wing2Xx1yV3CJq0SGC4dWffxpn17t5g5MQLuvLI8=,tag:IbDYE6VZzFeQjaxwF1LGDw==,type:str]
    PROWLARR__POSTGRES_PORT: ENC[AES256_GCM,data:qcw8jg==,iv:/6s1NsxU0eV+uR3ZMPp95iIcF3mQdX7XKeXal6zrlVo=,tag:ffo8IHJQDR+oVu+VUWxO0g==,type:str]
    PROWLARR__POSTGRES_USER: ENC[AES256_GCM,data:7x6d4OdatJg=,iv:Q0nRTHNLtY0d+gyJEOCmBWOAlIy3jX/PzA7cgaotg3I=,tag:TOI3vsqtlr1RY07/aDInxg==,type:str]
    PROWLARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:4gPh0sVCFGZyTHNqVmy/NhfQjoKQlx0uxgHtxzAonsTMo5HtKgRdJix/eIkAzOhL2nNXbWgEAHNUeGJcuiTz/w==,iv:2ZPq8KuWYqcsAv9/QyICZMS90RmforpQMn5BX2DPfNo=,tag:rdPymaIwDEn6Tsg97Pwf7w==,type:str]
    PROWLARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:+jsB510SVgESey0a4g==,iv:qkP3578qAgxE1emEkU0gg//rW9HTjdBAw93t/l2MS/s=,tag:q7NVYjBBmDr049Ie3nAW9w==,type:str]
    PROWLARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:HfkgZFd6x3h+ZdBY,iv:XlHTaWgL07PqazAE9gEYSMElistcDpF0Xp6mRemLEfA=,tag:9N3ryihD0Ol+5mBGZrOb+A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:L9w8ZmTmxINF1c5+ce1HmXHjd7xGmhR5eM0=,iv:EkKfM6XxpaSGbrqgtGac8UE653tNZkYj+DVG25BquqE=,tag:5G8GrnA/fX3Qk8wAV5fXPg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:5jK1slqGG2Vs8hcqWrnnqo1A8FEnG6yn9plZqzi0wN2IFtcFjN23HA==,iv:7UAVESUplwaCTvzuyZQFiYllGfoVx3ANMVDKMzgq0Hg=,tag:RWs/cU5iorWRCznGBcEg0Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZCHSo64pcuc=,iv:ePd5HO/gz4jDcFR1GLhC55RxoxZIZUVNtv7beWxXZCI=,tag:f+o3XKhypK0CJUEUIYTDQQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZNUNfjY9mLcVuUDQzXrcwSAokiMuHviNP2JIHL9pU8FQJc27T+moKZEQt2ZjjgrgqRxg1kHfjIPziEBcabHJsg==,iv:ODV3mtgeCtlQTND39k7zgZdbj1RsjCEEeXKV49B2Iu8=,tag:5MHHcJF6eXZQIGppaaJ+og==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:aYEyvy4Ya3ExCYKaI3hds5XDl5vBx/fAIzF4MiekUuhekx7gQsF4k0PhM4/R7eLdcT6YpLxmAObfFQuUmVPvGQ==,iv:Nh8HbAE7Qiv3no/uLJRpzwLLl+jAGWUs0Q67LSxdR0E=,tag:83c+zb+R1fGy2lTVNLVrJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3RueTdYakZ0Q0JXek9l
            aEthMHAvRkwwdjc5dWszcFNMbjU4Q29SY1M4CmtlcjhRMjNHdG1TNUx0a1FIYmNF
            c2hnWE5xSkFLWkpwem0xdFFuZG1SWlEKLS0tIDFJMlh5VUQxdXB1Zi9NUVNlMFJF
            YytGbEQzMjdVaGs2RFJ1b1RNdFE0NWMKNiPpEpL01Qu8kJEx6Q0bIg6OwiTpD/Ea
            M0hxgUkG+rVZS3A61j7rFqefTi6km1VmKK/OsLuKkd5oUOjDkdTbOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T17:25:51Z"
    mac: ENC[AES256_GCM,data:yNSzkMeINdHFJmMqesPelhFT40Cw2bMDDrR+exxNNeT5Ygt2cJG25ayN8hvVOU3705ZF8Y8rD6OHgU+sBxMd8AmfN1mKYL64rglfCiycvd+kIcxUcCPB8466FifF6a0Axo32PaBn9//6+uRlgYeqozr3sBpmuRn/ySWMtCaXWH4=,iv:i6IrvDRcES+fdjCGhq0sb+PctT2MZZL6vTm4RG2vrP0=,tag:SZe21OYXVFT/vk+ZK4vRyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
