apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
stringData:
    #ENC[AES256_GCM,data:9qKYxKoKT9LtI6i0c1WjFnNtLn7bFhGuTrPk/mclptLHx8gFUdyVq7k=,iv:W9Xi81qYgX8BmI1Cc/OHoKBfL5j6J5Wun9xqc2LSsM0=,tag:RibrfEOsrE1p4ih4mpuENQ==,type:comment]
    #ENC[AES256_GCM,data:Di1xMkqQyKFZSjFh2rMKc8W68tNK+FR1tz3gJRfu28HsfTXjO9SCk2yo1Q==,iv:r2GEwFynnSao19HpzS91iIDy4fO9oWZgmQvWmSLvKZo=,tag:5Tn9BLXjCosgcNzuTLU1dw==,type:comment]
    #ENC[AES256_GCM,data:QUpTmU9AZVVQ/rvBT6MIOoZrmcc1y/Q0f0rjZQN+aweNTtQGl4DdTbg/MQ==,iv:BsseBwC6xSjmoZRZXxmNlOZfcuhaLqP0aOy8dWjGE0s=,tag:/DIm41LvLzCuZN8eCygBuQ==,type:comment]
    f: ENC[AES256_GCM,data:KA==,iv:npBJ7ZzvL71Ci3FEiDAV9PRw+6GTub3SIolWwyECRnc=,tag:VQLjHcTnuEEV4RhVyw+fNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3RueTdYakZ0Q0JXek9l
            aEthMHAvRkwwdjc5dWszcFNMbjU4Q29SY1M4CmtlcjhRMjNHdG1TNUx0a1FIYmNF
            c2hnWE5xSkFLWkpwem0xdFFuZG1SWlEKLS0tIDFJMlh5VUQxdXB1Zi9NUVNlMFJF
            YytGbEQzMjdVaGs2RFJ1b1RNdFE0NWMKNiPpEpL01Qu8kJEx6Q0bIg6OwiTpD/Ea
            M0hxgUkG+rVZS3A61j7rFqefTi6km1VmKK/OsLuKkd5oUOjDkdTbOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T17:17:49Z"
    mac: ENC[AES256_GCM,data:5k9h2RbFXzb0zre6w23tomVLvKsZFNkgs5p0nxMaToDsuKoGJmUuODdK9eg1OgKLVnHV5ykZcunsP/hatHLnY1zpe5gbf/2t0/CTIdC02hI1Y9Ory3P8jBd7OfFP1pw7ZBv9uyp7I4aYS5v5DxNKIIwIvEDKZAufArTDUv2LN7g=,iv:6Gq0z+LbwQOWOuGbjheWDYdf35/Rtnz2Xtc2gDwDGqk=,tag:B5n3e/cUMCPaZ+0Z6o2O4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
