apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:OhheBj/qpsxnLnWthjTSg57/FsRnmBFwkhaMRC/Dh5Q=,iv:o54fEKdhLBSVRUQDoqMrvWfDsF1r7saz+FEcKkeZzP8=,tag:SNY+kFe4O+s9tCeXOhEZUA==,type:str]
    SONARR__POSTGRES_HOST: ENC[AES256_GCM,data:3+k5flcFOSsSp0EfnB53jcaRO+Rr+VuR9snIU6Aard2Ql8ov9CpCOg==,iv:1QqQRJ9Y8AJcChXifRXujRPFjSMDEXN/Dp0kK/2u5jo=,tag:34ZnTcg9VXL62wbINR7zBw==,type:str]
    SONARR__POSTGRES_PORT: ENC[AES256_GCM,data:9RpfgQ==,iv:r11xP90MU96zrkBvyKXMKyCgVg5uPtZvlSIuJ17jM/M=,tag:+SiSa5EQL8YvBjWKErf98w==,type:str]
    SONARR__POSTGRES_USER: ENC[AES256_GCM,data:DByN/Jc6,iv:iSKE/Fcptqj/BZOikVVEDVqDKnte/HmbF+z5tl6JrBE=,tag:PM5hYMRkj4MTCbPQD+7olg==,type:str]
    SONARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:H0thqGNc6rhqNjnrYWawd9lJ,iv:hTX+HEKLggIHTxY9g9gCWks+w1X1YLTYO8WgeMI9IJU=,tag:YqzEJ8lONDyHg7zBQwGTsg==,type:str]
    SONARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:O/4VGP7wVfSFaHs=,iv:0xpd/UwHlJNC5EwLc6F2PK7llZzPDe6eTo8rqQ4T+nI=,tag:TXop2HkPJVHFBwGFIk/k0A==,type:str]
    SONARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:P7YFrpuTHkCMeQ==,iv:4z9sN1aM/qt1HMzG9Y2r79zfK1MMsR+zh0oC7bqGFkQ=,tag:WLdhK52z1G9DaClMF5I0/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NWdlY2tIVmwyNHM5VzFk
            VGpXcmtuNlhZOE9xdlNwWmJZVDA3ZlBvMlRrClZjNHpLRXpJeEdydmMzNXZsdEVx
            RkRhNnRRSkdWTWVWSTdydjdhK0RUOXMKLS0tIHhXQjRRQUQ3SHZHdlJuT0hGbU84
            QVZITTV3TEU5OUJCa2RJYUk1UHVIbjAKOHS8yMzKiZBtCibUkVlLrALr5WbrFgzN
            JZcGDGKqkQEJFJndUvyQCAFQlmW1hYfJC0G8U+17E5oSJB9PDjnr9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-02T16:19:57Z"
    mac: ENC[AES256_GCM,data:9/9xmO5gfNWXNYzQDC5E1o1Sz/qvZd/YjPKdhghuJ93E8V6ty34x92aXcKqLxamcrdx9WOAy9fxEB+DvKVwH2Ucc8/DAxcoURuQeat4xuMHqmgpjzxE2k9IHyZfKnlNsOAqpWNEI9Pjjua84/yifGuPZrpITpDuAELYtH8Ij6xE=,iv:MdMN2EEaZvSiGZBcFQoyz23zlxHyGhC9LruSxyeCLgQ=,tag:vQAGGXPmKTXffQFmvBdtDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
