apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:YFhMRrpVyEFMACywX8WPQ5HZwBFdEhc+mbNGCcTth/kz99XFPjE4vQTPtLT4RgL8y1M8Ldy3YYNPAigO,iv:aDYYqaBerY3djxNkQGlMbADLlvUINaIpbK1dukhYnGE=,tag:lEtwe7dYvL0x1zhwrUYEfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWmtHZHFldnhSRERwMC83
            MCtCN2ZOZ3J6NzUvMmJWdEZjdTd0a1RtYmk0CjUvRVB4NFQvNFhJNUcvSmFMUmp5
            L0hEbm0rSXRzaVF0bGpRN29uVjhuQmMKLS0tIHlxeUx6TXUxbUZRSThqYy95WmZE
            dXlZQ1drODFyRitYWnlMcTF0MHZwNmcKJLTRv66jv7HQtMyvaKo6sNcLhlYBcDqA
            Uqb42PO+fINCb1t2jzGfU50oDztEqX4hXKE1wLHfQfExyu5feuWBwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T18:39:15Z"
    mac: ENC[AES256_GCM,data:i6wX0ZMCCcQTEQrM0+BqDVah3AATyrfPeJyJ16kjw2PiMCL2dqMMa5E7cuL7HyPBW5hoYv0/RQLil29n5JnA/FAfYY2/gjuVBcrFRsXYbSzM02a/QwVoAYrYokgjwjdwt2PzVPYuY3zhN2+tbdLMoEbi8p9M+sWys4TXxOr2uw4=,iv:1AgHQpDSDUHAaHrKcmGWq2o+AhJ+zx/TkKAeddjqUnc=,tag:FRSP4e0w8vSis0OWDQMSHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
