apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:jHMhsR1n+cmsueqK+FCrYLbFJ9YVh/usAw8DdgQf1kZjC6PFpR6S6kUqanx9Enkcw3IovD6C5GFkizNP,iv:kYoe4boijMN8r1AluzgcIUGXgJR638VPWtC1Xv5lsvU=,tag:JEll4GTwsL4TYnGA5FfHeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWM1QkkwMDBKc1NIYXUy
            RzRZS0RJME9tVWp3TkVkZUd1MWMrSlNiTkQ4CklRWG9lOGdrbkIwdnR4QzAyTUcx
            a1cwS2hGVGZwRE9ySTNVWmRFamRCejgKLS0tIFlIYlpCYTlYVkhPRzVzekw0MFk0
            RG9hYlVHWlNPZ0VXTGxISkorRlZ6OFUKHqMiNgFFS9tu/Jb2ox3ToPloBznvAdvd
            OBd7DxedHN5E+ioNoIEEtGxjOh7/LKpAfEOFjm4XNjjH+lOP4+6kBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T21:51:57Z"
    mac: ENC[AES256_GCM,data:KD7ggERp7wAA0jXC0hHa0z5EjRr5WcXjQEJ89cWY1IjciBzKrZGCmQx8YOZgP/6HUA6ltaXj3sgqgEwV9NruSH0L26omIvVmLq8+LlJq9XxyQG7bH1Nq59dHMdMjKT2IszF8RnhL+wklPH9YLDUHsxCDojTegNL0CdYtOu6euq4=,iv:DgPAUIHU9agSG8FNBGfdOqjT3OPgO9QqF7Ef0bU+o5M=,tag:O07HVYoqkN1iX42Fff44aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
