apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:qq40ZUgPveI7Sz5zURO9biRg7c5bmKEGdoUos9iyofEZ9p71UiREqCgDzNbpu2BhQWoaLqJ0LNdNFbmC,iv:x+3gL7tLwu6XH8kejdzjpiaTT3H2UoJKeqJgcKJGk7Y=,tag:qQz4guf1lv2Y4K6D8bF1yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbmRaQmZKNXF4R3Z2S2dw
            dVg0eG9nM1E5Z2phUFFScU9vbVRVdnJQV0c4CkhBNGwxM1BxeUxEcDhnclM0QzIz
            VTNIdXZQV2JGMDFVaERaaDExZ3JtMGcKLS0tIEpHN1UwTjZISDlWaVBiVk1vSlZx
            dEZoVUtXbXNKai9VUjZtT2djNTFVckkKZOv2RFA4qp4XDW4ergU0HS4/XsBzfVNf
            KDNS9JAy9umxTRSVol5P4A73NvEmyM08DFo02yrVsPt/XepYjvMoGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:22:23Z"
    mac: ENC[AES256_GCM,data:rNNWAZ+2fKjWDSdkOL1Ya4apMshmEj49Dsi9x3KE5dlb5BxjOQvLn72keX5JCifFR31lxxl1fEviJ/GQHPvo6qcnnzntWj/pC4EjM0cB4tuZPGuHgnMk+RuKXzpqqzah6SGyxgpCuMOkiQm15fur6rM/7OQ2pjTOgbTKgea+V5A=,iv:pshDr/zHI8sH3ZjTAzZ5Sd2NE9FvW7BGFF3VS2M8XgM=,tag:GFbRxb/6Ho3FdoAKm8E/dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
