apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:A5iY3w6efginIHXATeYTU264jIvWeoO2KKONhjQX15o=,iv:vW71omRBIHWE1cnb4PwPb9QmG3YKmZ0pCOPr4KX4JlI=,tag:q92Q3hto8GReuSTLU0ZPFA==,type:str]
    RADARR__POSTGRES_HOST: ENC[AES256_GCM,data:tHhfPW7n4+TPAkdTpuCnMmRi5jwGjRNS2hYhLl8VlTgpH+/UmREntg==,iv:3xxKSNXhqynM6f0klFsQUah4vSCo0BAX1un9xhDGSEw=,tag:Kl3BaTfgQpn3R8rdxszFmw==,type:str]
    RADARR__POSTGRES_PORT: ENC[AES256_GCM,data:2dC1mw==,iv:uhDMTK4gs+ET0dRKvtQtf1C04FV3KbfoxGim8HhZdQs=,tag:ZuG+samy8lKjCBmd3Z83GQ==,type:str]
    RADARR__POSTGRES_USER: ENC[AES256_GCM,data:dgtIq+Z0,iv:pRarkvg1jexZ/IHjSYOvaxljln+lfALQAScsPnwje58=,tag:Lzm6EcyMgLrkv8WUFIBTlA==,type:str]
    RADARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:0KPzeCPsi8VNJwviC2GWZUVC,iv:VV5G+hY2nn4YYMjEqA3UNwESgfzOuHQsERjBtMnlN1g=,tag:td5L9faotLPuHWw7xBaigQ==,type:str]
    RADARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:+aKkfNQne76vCEQ=,iv:Zn9/im3S5EaGmmqH2euLy4BczuSwecPTtWYFBkm7RHk=,tag:3NAZjaaR0XwHoK8zaYy8dA==,type:str]
    RADARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:zDtGydmr7V8tzQ==,iv:v7RaP+kL8OyTT56lEGgsf7pjQNOTy500E4/3+QFwBWM=,tag:3kYKIatbwiNE9r8PM7zX+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK2N0N0FoaTBlZGl3M2Js
            ZEVhbXRBUHcvdUZFSTM4VFJsMUM1SXpENEZBCit2SEFxdkJPRk1yQzNub29jS1pI
            OXhxbnViMlk0YTFNZ3lTa2xFS2hLKzgKLS0tIGVCakZpbVJOaFVvSTdTbk9mcGpn
            eTArWnNsMkxLeHlNQ25qTG9FQXpoZmsKFJkspobfEmlquT+CZhLBsjeqjWxCQc03
            rFnnfGUK9bQtK9tEggMW0BYk6MRaFQrIRgyHjNW4Qs2QCWZ74zZrqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-02T16:19:57Z"
    mac: ENC[AES256_GCM,data:JqM25j6dy3h7c0l4vqLc8dHcqb0n72749pR5wuOL+z/On6RY3hChsyothGErsWFPpDzCu5dtHW318oVEI1dSFnzd8eeSdlg6M6rcuRyd/L2f5LTG5ImqLLY6LeZtaw1poJ0WY9Jc/f/JTQIOm0jGZKnLEen5RqwnS2accNTPWsw=,iv:bPcpaB2fUoIq5UwvF0590ZTKTJVQgMuLwlmk5z7tYaU=,tag:x9yGts5zyas7yODFXu2bmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
