apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    #ENC[AES256_GCM,data:msVO8ghOIwW8/SumiDqrJDzNHOkoP6jg+5RGbNdMFViMlKs25lpKtS4=,iv:jGK+hvgBaifh60rz6Pfqw+mwJT9RWSKGXhl+LnwMN5Q=,tag:vvPQpqa+cfCgmh6KD9+kaw==,type:comment]
    RADARR__POSTGRES_HOST: ENC[AES256_GCM,data:xB5A7gawBQXVhnMZgpYi6KV4WvFwgP6JE3vRMqjeXiVeKqUEUnK4BA==,iv:a13bt2CcnUv79BfYEwCXk7GFGBJNiJeTUktXCM8XXUg=,tag:dJzX6ztjemjD6TJTejjwjw==,type:str]
    RADARR__POSTGRES_PORT: ENC[AES256_GCM,data:ODpj3Q==,iv:GtbyNqOnwUTn8UgZdXlS7aX1iCech/J/iTH2IMg2yOg=,tag:TqcKL3ZsHZSfM2JzkX+huA==,type:str]
    RADARR__POSTGRES_USER: ENC[AES256_GCM,data:5/Q7OPlGEMw=,iv:cETUdpTb2C6Q1jaIyiAQCy7Cq30SrniqRN0BOhWTeio=,tag:sZvfnsOCPj6sCjGSq4VmRg==,type:str]
    RADARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:/R80kkSIpIoy1lm4W7mT9kEMHaiH9ohARCNg8J8jwbnP9l2pPU1u7YSgiQlStT7c9fyri2dOhMJMW4ruEkYACQ==,iv:oQv6Gc6J586BT7cH3L4oNMSWL4Yaz8tk5FYtekUoMrA=,tag:CFs9y7WMOclnuh93OMIeaA==,type:str]
    RADARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:WKNbxdEiTyoAPzk=,iv:tNlyYdZmZhDzvvbe1bbbNYcWVeTfBkwJv627tMkKiJA=,tag:HYQCWln9kEYlQVoezdOU5Q==,type:str]
    RADARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:JlrdhGFyS9xngw==,iv:DqOAr3G8XzBCHx5CmldDo3iF0NTXU/T6GtOtgRGx0ng=,tag:G8fc+Jewn0yHqYfXGrJYPw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cRvGojIJ3gO0AkCOwpHdO7N105TCPw==,iv:y6PAWLOqUEjpUNl4LW4cKDtMFEI61/qkLE05wG4Qsk0=,tag:iJBF/TXYGLva7J6xNe1dSg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:5jK1slqGG2Vs8hcqWrnnqo1A8FEnG6yn9plZqzi0wN2IFtcFjN23HA==,iv:7UAVESUplwaCTvzuyZQFiYllGfoVx3ANMVDKMzgq0Hg=,tag:RWs/cU5iorWRCznGBcEg0Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZCHSo64pcuc=,iv:ePd5HO/gz4jDcFR1GLhC55RxoxZIZUVNtv7beWxXZCI=,tag:f+o3XKhypK0CJUEUIYTDQQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZNUNfjY9mLcVuUDQzXrcwSAokiMuHviNP2JIHL9pU8FQJc27T+moKZEQt2ZjjgrgqRxg1kHfjIPziEBcabHJsg==,iv:ODV3mtgeCtlQTND39k7zgZdbj1RsjCEEeXKV49B2Iu8=,tag:5MHHcJF6eXZQIGppaaJ+og==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:aYEyvy4Ya3ExCYKaI3hds5XDl5vBx/fAIzF4MiekUuhekx7gQsF4k0PhM4/R7eLdcT6YpLxmAObfFQuUmVPvGQ==,iv:Nh8HbAE7Qiv3no/uLJRpzwLLl+jAGWUs0Q67LSxdR0E=,tag:83c+zb+R1fGy2lTVNLVrJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3RueTdYakZ0Q0JXek9l
            aEthMHAvRkwwdjc5dWszcFNMbjU4Q29SY1M4CmtlcjhRMjNHdG1TNUx0a1FIYmNF
            c2hnWE5xSkFLWkpwem0xdFFuZG1SWlEKLS0tIDFJMlh5VUQxdXB1Zi9NUVNlMFJF
            YytGbEQzMjdVaGs2RFJ1b1RNdFE0NWMKNiPpEpL01Qu8kJEx6Q0bIg6OwiTpD/Ea
            M0hxgUkG+rVZS3A61j7rFqefTi6km1VmKK/OsLuKkd5oUOjDkdTbOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T17:21:51Z"
    mac: ENC[AES256_GCM,data:2Xop/RC0bmgEcgsboOmmuzCjeonildQnGMwFfu6GPTey8p70A8qGkTvD25EGLSXaq3ov7f6gvp9StqtfkwzfMiAPzjO8qzi0eoZbVPE3vhuZqW7eqam91Kdti+5KZz0HEhcZ4yDh2Nni+UCcEDGQtNpVoWoUuhuRdLOrOZIkHSk=,iv:Jvy5Kr3wamSLOEJhENkGs13jBVXwauosne6vOAeXmEg=,tag:XHZmrFTWnmq0P8fJ99McFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
