apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+viYpbnpqfQwoBSd8g==,iv:0Rm7O+qVmHVaT6KXEUO2XhJ+Ob6JVwLUEFCoVhFLiIQ=,tag:8kHJPfmAvGJgAC0Cl7aWAA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Cr3TjufCyEPqQ9zZbPDQWQ==,iv:NCe7h7hQsdCO32i8x7lmQaWO8CaPeswLe4UOpTy+qBk=,tag:dQeRu5rXWDcK2UtQJRWBWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOEpzclVHNGFDc3hxTWlF
            cE5EZXlBMTFXUWE2dGZxSzBIZGdDbkw5UkFZCm1QUHRyY1o1Wk1HQkd3U2lXL1Fo
            dmRJa3JXS1JKVlJKd0dkblBvbk5FWUUKLS0tIFQ5Yy9EVU92ZDgybkJsSGVIV0t4
            TzlMeEhpc0RLTnZ3YVZSZjBCeGRmdTQKW/W6Xjpo9LeXtpxvy6c+4b9XrbJo0t4Q
            ErX+EkyM4+Zf5VF1E2Ob/HL0M0V/8KRFq1KLyczcY2FSl5nezbdb3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-01T22:46:47Z"
    mac: ENC[AES256_GCM,data:w6N/WgUy9weTXPj0Bi7Sju2ntRqMygPwGaEWk9f6vOMWfhJiDfRwm6fgL94Z/gsVBRnRvKL+5WuMFOSnGFBteD7JIMcfhjRiw2Bp1wcQMuiW2ADfjRhyoqmcXWd2zxiq3K5aJJmPhay2S5ZiA3QbGlSlFgaHxrjZkp+LnIRycos=,iv:OhgfwBJbNl5IpBzuKM3I9r9F2jwLoa0nol1Qp8j9v7A=,tag:/LO7H7YKKztEDIBzEoBkaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
