apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:pv6//Mparcxuecb5,iv:B4yO+/c+qrcGKwMR/vhWbu9vwcDZfJsU4TiAbyXew/o=,tag:OP5T3liiScPkKUUTrqScvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcFdOUXlZOW5zMnA0VGFT
            LytjL0NmQmp4M0Z3eWU1L2w1TW5lNWlHOFZRCjMyUGVyVmlJN0t6N3pXek45UUFm
            UU8yaUNMS1ozeTJTVXFnbG9XZm10alkKLS0tIDd3clFhUWhoRDVyTk1uOFdJMjZv
            M3ZSaGhTaGFtSnRpLzBueFBRN0M3ZFkKHf5KtW5Hfjtqm/ZBVUNN7YXJ/Ka/U6Ek
            FCmmu1+tlVKtwPBBC3fKwsxtblbZL2Cmiw/JlJfK+e4484cnYUgvAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:Njb/d+Eit93PYknhFOi+eAt5S6wO82b6WSFa9+3xO2KqKwhMD5R2cNOYYAonORUv3a9hxz28We3u40VdSa6+PwKaV3iG3LJU9pEt5o/IHWTmoXln580aQhpBovSqj/YnjbOPMjBaVe7lhwjfeMPRajWel/WVU3ty3Vja0gYWwIY=,iv:NVVleEJjKSAhwBW+RQSaEcpb84B6wjdogoOqMJKoulQ=,tag:7g6kGLvb6sn/pySFUBy1DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
