apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3lfg7oaBNmdmvZwwDg==,iv:BcR5yyUaJ8/nTJaE8H/TBDE3O1E61lzMzxs74FvcD4s=,tag:hpBUCqzvKo3LomhGbfcUNg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:u0ThznIm4QvNDB3bblV6Pw==,iv:eRMXsd0SfGIZGaWfJpBxsI6SMzdZ6Ns29isPmpAf8zk=,tag:cBQ7CzH0IqWCi8xf8H+FeQ==,type:str]
    NAS_HOSTNAME: ENC[AES256_GCM,data:hf2dh1SRNnIKv9/6xFj42iq8uA==,iv:0QgD9oayV/vE9iO9+2OF8g/bisi7dn8NLBYfzVP96c0=,tag:jGxUA4tMuRfN9FzTxUQMow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRXVjZGN2LzNYa3JBS0ln
            NlJGU2pXa3J1cFBnSUUrc2J0NUhoT3EvOFY4CjIxMzRDUFVxQkdxc1VYdnppdGpD
            VlU1TGtrWmQxZU1qd044bWtzZGg3dG8KLS0tIEhwSHpaWHpobzVZQUs4VFdSbk5F
            LzNCcitLdVd5dE1ZQjhISEQ2KzdJYVEKZlfolDHLvFRefNXd7Dke6FV85RvHLa/W
            t+1Ob6a7W5mwGIf0T6oQiQN5gr4O+EACW8QsFPGnX+bH06cHatrVkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T19:43:41Z"
    mac: ENC[AES256_GCM,data:4AVbE1NNiKzsk2uTwxUaOkc8FpW3ymgpSbpg6YdgSWZ4Kh39UxkwMO7wmcGLtGQ/4cPA1CK3IJfwLvZr+WtxlW2Ce4DJyLqZFiSD7icz6x5nDloe9IMyoC76IVQZg/6t5/3hcvmHFs2Ov6DRWszdB8DZl607xtp2SmV6jKRpxY0=,iv:S2NcklWET2KSjSKlx0HH9lU5IjaS3j+lPeaViQjUYj0=,tag:6dbMyvbehRjEYOSpkFY0GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
