apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mXxJVCAoPmBrh3V1FA==,iv:alXccRyGzmmPV7GZj2SxNwYI1/9ntlSZDajsAAb0BNc=,tag:Vr2Ho9afq9bVhnChOYnzgg==,type:str]
    SECRET_NAS_HOST: ENC[AES256_GCM,data:733N5zHG7sKLvl5tVkJbqqU96nA=,iv:k68yPopbyp/22c7pPjMyFr8AKGmT6IWaQKVTopNlja8=,tag:dd94kvv4uPC60yIGEOaY2A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JidCf8CITPjjvjdcdE5nR3JG,iv:QRCbSbEIsMR0696a5U8K2RX+OmBmJwj1a8xQmCe8Z8o=,tag:ARuBFnbi8GDSnFCKTUnQGg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EDyOXzKv7ZWYFl/bJavMMIrRCDT51mcnzYq82Nl7Vbgw2DAs,iv:ewSToju3waZLvvumCgUruUbcaUXGeT1hrufUJvJu8Vo=,tag:ZXiGSyf/r79hGjwlpGsMeA==,type:str]
    SECRET_LAN_CIDR: ENC[AES256_GCM,data:HeoWcgvJ3f14o3l4unUz,iv:RIho+LF6SF3mpfrONHJjKSVOXMlhiVIt2KrB86DtdIU=,tag:brj/We4zHphhq8JSyu7JjQ==,type:str]
    DOWNLOADS_VPN_PORT: ENC[AES256_GCM,data:SYL3iLc=,iv:JdJvyVZcQMeFRgrJqQLEiYzA+RasjgqtJsSuhloGvFg=,tag:YtOtLr5Y2URllBGlCSjHBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEanJxdGxxRTVLTEowTmxS
            YTg2QjA1bmpGTUVJbWdlT0R4ZGMzTHVuMkVBCjI5SGhCek5JVGRsdUFtMTZQeHk1
            bzhJbllNdmRPWlcxVkRGMmsrTDhldmMKLS0tIHM4YmhWS1d0a0VhZEFSMFUycVZD
            RDlpMlpSakxJeFdva1lJRUp2K3dTa1kKbaYcYCCaHJzvBiVeMtZe829EryLtkSL8
            hJ6k1ZaHpMr+P568uMWaJB7oJzhMQrVphN/AOsWjAXLtVnBsk270Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T14:55:27Z"
    mac: ENC[AES256_GCM,data:NNt7cDnvGh0XeoiLCVxSVlCQcCZRSgUHkbnmVmmhYWRqvz6re4Jotts9mHi92M40fcS9V4HBEa8PZSLcZszYn9pO4kL0VrLZF5D8xFqbi5XbGP9XadA5N7hWyQtbNEFm1utyLS2tubFUlxwuK0qgP0hf7GY5JZmwu6P9YklwNYQ=,iv:F8KPur3zmAerfVxh9yvxdii+RKbhZI7C267yl1Kk0IA=,tag:tW7vRgPNQPy3d6CnOwfizw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
