apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rJkI+8ehJjvW8X3Ek8twG6vRLs5a+gUmNTOex8TwhMQ=,iv:tqKVgVt9rUeykURI//iY49Nki7T6KbB8R6ZpK+CqE1E=,tag:b2m5jjDnXRgTLJ47uDRrSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUkdlU3pZOFMybG5Yb0VE
            ajdSdW1sZ3ZSK2x3cmd6MTYwODZlUnYvRWxNCjNWTE5PYlV1TENVdjNHMkV2ZWRw
            eng1N1lRZzJGY21FRnhyeFRHRE1CN0UKLS0tIFFvUWlBaWpUNTRjZXplMEd4Wjhi
            RzNQNGJvZVl2VGt1VDhDNm9RdDc0bmsKx5Uju7FJrK1FqxeHIo2BLUk0fQFRC02V
            99CHctsSij3CNYIL+1715ugh2LtT32r2WeUWBQeAXf6K/xYXItAfRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T18:12:29Z"
    mac: ENC[AES256_GCM,data:YlcEmbdbIO40/jnBAPXda2/DMBtlkNuzcvLCEQwUDwZ1Hr/An23OAuaL8W715wIgAHOIYwPJWzvOQsamEe5G9YsJWctTzi75wPo8jqm/AF/3vZShOmUs77yc+Q1uFudij8j7WFRh1QoK6DhZqIiYwWAiuECVwCZ93OZy+zmFPyU=,iv:bm5T+uE7vuvzK6VXOi2amABBk+ttTA92r7WMVQcpg80=,tag:06pWbkgs0UKy7Zl9xkpIJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
