apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:/AIrrqtoJeJbUOw2z9qPMTFeOw7aWPtQ5xhfq0kctcQ=,iv:kH1GrdxeiHEWPJvB1g+yn/n+te+SuLjuoXOzJ05tfm8=,tag:SCGA0PomILKxqN/b01TcPA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:JWhhCr1ZQvOfeAqNap5vwUmWMPLUNq4ANbUH40KiuGNeOIVC,iv:h26shpDeIu+hMr1Ma3thkp4Yw20e7vKrHpLmbbpSYk0=,tag:T9R56w7p1di8g582MY0klw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:CuMdij4RAv54qBQLLMXALM26v+RC9GvmGr2XMGMX2dwffk3U15t7Ow==,iv:UnE5rAAe6oeNZEFrwJAmIe2l2c6cfY7AtSm9IJ3U/Dc=,tag:WTnAWsiq65Oe9ALtUE3q+Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:IW1AtiI=,iv:jfCShy/KGT0UgRSfWBpnvZj9KdMLRQ5KqaGtYCsNHVI=,tag:VMga0RJJgF+VNCwW9goHdA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:xcWZoePp86Qt,iv:4IbW1AyOBZiOFSBXVvjfaG1u4Fw62nhRd5BLK26vKDY=,tag:aef/aporDPUm0Ht/5ooxWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3RueTdYakZ0Q0JXek9l
            aEthMHAvRkwwdjc5dWszcFNMbjU4Q29SY1M4CmtlcjhRMjNHdG1TNUx0a1FIYmNF
            c2hnWE5xSkFLWkpwem0xdFFuZG1SWlEKLS0tIDFJMlh5VUQxdXB1Zi9NUVNlMFJF
            YytGbEQzMjdVaGs2RFJ1b1RNdFE0NWMKNiPpEpL01Qu8kJEx6Q0bIg6OwiTpD/Ea
            M0hxgUkG+rVZS3A61j7rFqefTi6km1VmKK/OsLuKkd5oUOjDkdTbOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:QjHobvdVO5GpJei725CxtSipsru7RRZ5tI8hBC+7rcJh+mt4+CW4t9D3LK7ShNgTZiMnKf9Q9LUES1p/gcLeih/UUfzaJBraG05tYbT9Z84+95tnJTFgyVyndd5+6gS7f5M0DUj/4DrYTbPCb3R9VGpFCRhGAStKcEAkE6U0zSo=,iv:L95Sbz5LlyhqC0SNSnPubfU5KZLhjYV2I08FB2GcwjQ=,tag:wzFFGqkXnpWv4zz7arIdng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
