apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator
    # namespace: network
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:+uUh3N4PZZbocDgaxOw/8/0=,iv:V6P8Yx8kMDWRXLnaD9x07qHTIuAZpZUPnDKiqovR4+0=,tag:fO9R3nbL3tTfPw+GqKlSVQ==,type:str]
    client_secret: ENC[AES256_GCM,data:e56KQnco67rZSbG0cH9T8VSS6ScJOhqhbPhXfRxYG97kypbZhAh5kdae8nirUutSER4bxDXZTKVFxOUggvrcsg==,iv:MSRmkUwCrqsPJyUOW3k04pt/ieoDPAM+sp8+lScdpS4=,tag:4Z3qJKIrylFRrRrJPE5F7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WXQ3RlI4MUJDc0xnSVZK
            bTZTd3dqK09lWDlUb2VCanJyUEpGMGdLcFRVCklHQndGU203RER1THFnSk04bFFH
            NmRSYndkQVhQNEtuWCtBVmZmYjJUc1EKLS0tIGxFbkRmNkUreE9uWlhnTmhrVFlj
            dThucDJha0o5b1pkQ1c0S2NMNWtobG8Kg7qLF2H4ZeqbeLmBm9/bzwdSXmffSLtU
            BHSffy+TthghxFO0YKysqMHU8+2B3Fm3mSWLlx+aMzZqMhsYCcL4aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T14:39:38Z"
    mac: ENC[AES256_GCM,data:YAQ2PiNJ3EsAnt/knFzl/mVvFoS34hJ8fXtVOgVIF19PJAXnuQfioV25Ip9q5B2dkY3D6GzfmU8/OKelcZnlAOMoNMXm2aqZnsQjZ9f8SH9dXvoK525mI+8YdS6Vcj4EArgXlavRulWvsY5tuEME37bAPWJX1Am5TZoMGhN8Wc4=,iv:7A4zW6EydR2S1tHhM7EoxbWMdoRLonAaM+0ycO008Qs=,tag:nLRZ1VcQJjYNhDixQxrQFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
