---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-spaceage-config-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
