apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: default
stringData:
    FRIGATE_FRONTPORCH_CAMERA_PASSWORD: ENC[AES256_GCM,data:dnMiAohom68lY6u0,iv:o6gIsyTuc4dQmB9UShWt+cAQXy/MtRmw9oT5yJFPESc=,tag:3jXpXth2wizn7VscK0ferA==,type:str]
    FRIGATE_FRONTPORCH_CAMERA_HOST: ENC[AES256_GCM,data:VGrTw01NdMexcm1dYlwS8USKBSCk,iv:mxWQDyd+9vtGJvPYVlAYdhQbrhmjO6IN0UTm6pS55YU=,tag:J1JghP6ETYzjtxKupyzzEA==,type:str]
    FRIGATE_NAS_HOST: ENC[AES256_GCM,data:ek8CkYyRP4Pe4TrvDfBb,iv:dwWjFSFsJ8gisHDDQk4180PhPDoVZblqFmP1e2TI8nc=,tag:gDdzlbulwQjdtxWKgL1ZpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaczZIQWhxQjZZeEhhak9J
            U0RoTFpWQkNzNG9vNnB1Q2JVMm1FODVBalJzCnBVL0JpdnhMdWFPZUJEaTBMWmNQ
            cnVYdC9pZDlVWG8yZVdGZW5Za1JKNkEKLS0tIGZtekFvWTljcWVCZ294OG1kcGtZ
            UzRYUklJZE05eUJLamluZm04YkcvU28K9aLV1xMiwQjS4BLgNQiMLiV3+DI1f4mr
            ++hC5WHkbY2NJsgYii0H9wnYMZXtZn1wXHvvAsx2hAXV+4jSaA6thw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T19:40:39Z"
    mac: ENC[AES256_GCM,data:C0yr0GcJDL5qFwx5c8oq2SXB6pG9oEt5NVxIcG8/oCfannXFZfyw3b0aJMMdsJVx00NNjtTrcpID4/LDdJKY4qeF5AoJ2pSBiKfoUYcC7/Abu12lhJkZF4cVBNZteqsH85Ok8wCVk/kIyqdfw051eWt0FZems15w+qOeZ9sd4pk=,iv://em3ubp8t59NIpRw6TNi6brAHYsqVoy3d3NmOOqxuo=,tag:7ZwQxvQ1LRLWu6mR4LDfbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
