apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: default
stringData:
    FRIGATE_FRONTPORCH_CAMERA_PASSWORD: ENC[AES256_GCM,data:dnMiAohom68lY6u0,iv:o6gIsyTuc4dQmB9UShWt+cAQXy/MtRmw9oT5yJFPESc=,tag:3jXpXth2wizn7VscK0ferA==,type:str]
    FRIGATE_FRONTPORCH_CAMERA_HOST: ENC[AES256_GCM,data:VGrTw01NdMexcm1dYlwS8USKBSCk,iv:mxWQDyd+9vtGJvPYVlAYdhQbrhmjO6IN0UTm6pS55YU=,tag:J1JghP6ETYzjtxKupyzzEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaczZIQWhxQjZZeEhhak9J
            U0RoTFpWQkNzNG9vNnB1Q2JVMm1FODVBalJzCnBVL0JpdnhMdWFPZUJEaTBMWmNQ
            cnVYdC9pZDlVWG8yZVdGZW5Za1JKNkEKLS0tIGZtekFvWTljcWVCZ294OG1kcGtZ
            UzRYUklJZE05eUJLamluZm04YkcvU28K9aLV1xMiwQjS4BLgNQiMLiV3+DI1f4mr
            ++hC5WHkbY2NJsgYii0H9wnYMZXtZn1wXHvvAsx2hAXV+4jSaA6thw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T00:13:03Z"
    mac: ENC[AES256_GCM,data:++YddVMEzASwFK95+opuE9ceSP35oytQuV1S0wbaId+sUTqbuspxbTZbEEXqKpQQFO6j2YnVCSu/+hrt+RWIZ0skyrsnSvJz20wGOm5nK9PB/z5GczaZychdlS4tIDHjBeaialJiYZ0F+4eNgAFjnxedJ+3xw84wRVvx63J/sKU=,iv:2jS5S3OiNi/wqx1l4zcNH7Y08qAjuZkGec8Ozq+xDyo=,tag:dq46dweBj8F1NapLLG8cVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
