apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: default
stringData:
    FRIGATE_CAM01_PASSWORD: ENC[AES256_GCM,data:kFhUol445SWP/UTN2xLY,iv:bLzn8/w+hq5FAWJZ5eB+O6THDv8ICo7tSTiOwC+c1Oo=,tag:bnKJHki2ijD1qC3MSJaMoQ==,type:str]
    CAMERA_DOMAIN: ENC[AES256_GCM,data:ar2zrQt9SiMxYbua9MX7,iv:UokhyHi7RWZRswEaAmigtZBTgl6KtqbaC2RDNNC2cWk=,tag:5kFPvnyuhqJmeXmw3fDpww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0aykey94awuclkp8uj3qmyt63kwxh90ykhgqka3dwqrvwyrmdgsgd8408
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaczZIQWhxQjZZeEhhak9J
            U0RoTFpWQkNzNG9vNnB1Q2JVMm1FODVBalJzCnBVL0JpdnhMdWFPZUJEaTBMWmNQ
            cnVYdC9pZDlVWG8yZVdGZW5Za1JKNkEKLS0tIGZtekFvWTljcWVCZ294OG1kcGtZ
            UzRYUklJZE05eUJLamluZm04YkcvU28K9aLV1xMiwQjS4BLgNQiMLiV3+DI1f4mr
            ++hC5WHkbY2NJsgYii0H9wnYMZXtZn1wXHvvAsx2hAXV+4jSaA6thw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-23T21:00:47Z"
    mac: ENC[AES256_GCM,data:7UicjBVewGpHt4+TYSUbBKaKZQpBD1Ig21qbejGTSgGkcq/6I6wS3G0rf/0+4zWBls6MYVOpPikwhKqT26PxtxfwbsVmQHDtnbzqFd4J8cpT+ciD53eW0GEIGi2xyYaCVUjSp+z7kMOtFVXVwQ1/cRz5+iSsaLbKrNxmY34vPPE=,iv:IrKpKaOfX0/MSpCTJGaT05Kkp9wqH1YY61NHgfvL8L8=,tag:bl/r5BxI41CVT9e3oFEEWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
