---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./helmrelease.yaml
  - ../../../../templates/volsync

configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
