apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:LjANqWpzYlyEwvBolNcsmCRKhrlzPAdpLnBj+Y5vzxEW4MqG2E2INw==,iv:NBoo2F924XRQeOVLLKHGR1o8KH/Q3ho+MsgHd8xouVE=,tag:8yjD9JACRtc5geerCGMgaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOTJkWkVxakZOaW9KMWVV
            Sy9ZZENiam1VOGhaM3F5SnVXaGFMNW9UUkdRCnpmMjZpekVpbkF1YVVNZUlQRjJ1
            NmU1bXNxRW83VnJYV2dwcEdrcFBPdkkKLS0tIERsNFZNcVJocTdkYmUvQkxUTHRu
            cUFkRVhsS0VmWm41K1pqakFXclNOZGsKfOlGqftJ2QtYUYJNzXm0bM2lrkJZAlGN
            A+6CGUTkuTsXv25/8Gz1mcr+rxSFGdOIGg2kxbzkCpsNpppGAsCubg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T00:14:57Z"
    mac: ENC[AES256_GCM,data:SfXMrMjcn/CgddsWNy2ICCzcGSe1slWY3v31sI8NL3Spk23rwHX2zR57ghvMfYyLralQvVUmjo+gDwH5t87j2cKIH4IG5Kz3O2mXaZya5RPn6Zj2zqS4redxg6+U5KSphvSCgEJdbedPX0XTm9PWq8GdPGx6i6fsnYByY3Taqzw=,iv:EO1a4DaPLv+rj96ZVmbu3mHwtSth5NOADhh9mwvfR24=,tag:MEO7OaQd5iwpHe2hkZJTJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
