apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Rc19LQ9ofrSXbaYDCZ0tcPDum9LBP00IfGBEuJWDe4iM/JtBPlo8LA==,iv:LfcO+Szig9a/b7leCX85C11d3KHldi0D7rRQYCi4I00=,tag:saaDtNPcJlMMpbjKZ/niYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwjfh69lcpg7jg48tlwrtmcqk6eg5zj07xamxnc3m4rrevhdwsjstnutml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VWl0blNLa2s5TlovZEdB
            eEh0Yzl2UFlrNGdLZmE1MmhDZlZkYmNCU0ZnCkZtUitWbXBpek9VeUk0VlNzTmFT
            V1I1UWZFSmQ4eHVhbUxIVnhtSkFyZ3cKLS0tIFNmNFpGT2pmT25qZjFBU01qZ2hs
            SFhBWHBkZjA0aVVTdE9pUmNSRUNxTUEKwW9p5TmCgrbrBYMAh2ffq+PSYsFCJOvO
            /uBcNLZGd9hPEzmk0EPukYFfM8EnWV7ukzaXwL6LSb5l+T3YkrUd0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T12:11:19Z"
    mac: ENC[AES256_GCM,data:BY2+vjbkS2zNfMv21nARAPGqjm77Hb1ceNGgTZ+AhAmniSxyxfZ85Y3Bt8vwt3s5PQR7ypo21p2tzUDcf7HBxcSo9AF6V6KiN7eAyR7oKz22CrHNo23dRiL/6UY0zSWtpYqqERVatNzydtC1ztMssYqjuIZIi52WkFInlv3jVx4=,iv:ieVVskTvpFZa/v88psDZFp5qT+cqhegwY8kEhlWEANc=,tag:SHeGjXPkXbQ0KdnOBeKHPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
